### ISSUE TITLE
bug: Unexpected token a in JSON at position 1524

### ISSUE THREAD

**Issue by qiuqiao** [tiddly-gittly/TidGi-Desktop#160]
## Environment

TidGi 0.7.1
Electron 15.3.0
win32 10.0.19042
Locale: zh-CN

## Description:

报错，提示信息是：
Unhandled Promise Rejection
SyntaxError: Unexpected token a in JSON at position 1524
    at JSON.parse (<anonymous>)
    at C:/Users/QQ/AppData/Local/TidGi/app-0.7.1/resources/app.asar/.webpack/main/webpack:/TidGi/node_modules/electron-settings/dist/settings.js:227:38
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

## Steps to Reproduce:

点击左边的仓库图标，如：下图中的public图标
![tmp57C1](https://user-images.githubusercontent.com/53331340/147448089-6589d22d-7942-449a-83c0-177beeb650ea.png)

## Additional Context

```typescript
SyntaxError: Unexpected token a in JSON at position 1524
    at JSON.parse (<anonymous>)
    at C:\Users\QQ\AppData\Local\TidGi\app-0.7.1\resources\app.asar\.webpack\main\webpack:\TidGi\node_modules\electron-settings\dist\settings.js:227:38
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

---

操作系统：win10 x64

**Comment by qiuqiao** [comment]
尝试重启太记，这个bug又没有了

**Comment by Gk0Wk** [comment]
建议TidGi捕获到JSON解析错误时，能够同时输出json文件路径。

**Comment by linonetwo** [comment]
其实就是设置json在windows上有时候并行写入会有问题。重启时会修复一波。

**Comment by linonetwo** [comment]
这个下次遇到可以把 log 也放上来

**Comment by linonetwo** [comment]
这是上游库 electron-settings 的锅

**Comment by linonetwo** [comment]
nathanbuchar/electron-settings#160

**Comment by linonetwo** [comment]
没 log 不好排查
