### ISSUE TITLE
bug: E-6 Unable to Sync, this folder is in special condition, thus can't Sync directly. An auto-fix has b

### ISSUE THREAD

**Issue by qiuqiao** [tiddly-gittly/TidGi-Desktop#164]
## Environment

TidGi 0.7.2-prerelease4
Electron 15.3.0
win32 10.0.19042
Locale: zh-CN

## Description:

依旧是同步云端时报错的问题，不过这次我在编辑工作区中换了另一个仓库（EvergreenNote），分支是main，依旧是仓库内没有任何变化，但是这次所有分支都没变化。

## Steps to Reproduce:

打开，自动同步，等一会儿，报错

## Additional Context

```typescript
CantSyncInSpecialGitStateAutoFixFailed: E-6 Unable to Sync, this folder is in special condition, thus can't Sync directly. An auto-fix has been tried, but error still remains. Please resolve all the conflict manually (For example, use VSCode to open the wiki folder), if this still don't work out, please use professional Git tools (Source Tree, GitKraken) to solve this. This is caused by procedural bug in the git-sync-js.
rebaseContinueStdError when |DIRTY: fatal: No rebase in progress?

commitStdError when |DIRTY: 
fatal: No rebase in progress?

    at Qr (C:\Users\QQ\AppData\Local\TidGi\app-0.7.2-prerelease4\resources\app.asar.unpacked\.webpack\main\webpack:\TidGi\node_modules\git-sync-js\dist\sync.js:67:19)
    at process.RebaseSucceed (node:internal/process/task_queues:96:5)
    at C:\Users\QQ\AppData\Local\TidGi\app-0.7.2-prerelease4\resources\app.asar.unpacked\.webpack\main\webpack:\TidGi\node_modules\git-sync-js\dist\index.js:160:37
```

---

log在此：（只附上了和这两次有关的log文件）
[D__常青笔记_qiuqiao.github.io.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/7784415/D__._qiuqiao.github.io.log)
[D__常青笔记_public.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/7784416/D__._public.log)
[TidGi-2021-12-28.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/7784417/TidGi-2021-12-28.log)

**Comment by linonetwo** [comment]
好，我估计周末重点试一下 main 分支的情况，之前我都是用 master。

**Comment by linonetwo** [comment]
老兄，我先关了这个 issue ，因为最新版 0.7.3 try catch 了这块的错误，并会提示下载 Github Desktop ，可以试试
