### ISSUE TITLE
bug: 添加工作区频频报错

### ISSUE THREAD

**Issue by qiuqiao** [tiddly-gittly/TidGi-Desktop#165]
## Environment

TidGi 0.7.2-prerelease4
Electron 15.3.0
win32 10.0.19042
Locale: zh-CN

## Description:

第一次使用，添加工作区频频报错，直到Windows防火墙弹出是否允许在以下网络上通信对话框，点击允许，才没有错误

## Steps to Reproduce:

第一次使用，添加工作区时

## Additional Context

精简后的log，从第一次使用到第一次成功创建：
[TidGi-2021-12-27 - 副本.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/7784475/TidGi-2021-12-27.-.log)

**Comment by linonetwo** [comment]
试试 [https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.4-prerelease3](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.4-prerelease3) ，相信修复了你的问题

fatal: couldn't find remote ref master
