### ISSUE TITLE
bug: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"D:\\

### ISSUE THREAD

**Issue by wyLeon** [tiddly-gittly/TidGi-Desktop#168]
## Environment

TidGi 0.7.3
Electron 15.3.0
win32 10.0.17134
Locale: zh-CN

## Additional Context

```typescript
Error: E-3 failed to config git to successfully pull from or push to remote with configuration {"dir":"D:\\TiddlyWiki","remoteUrl":"https://github.com/wyLeon/TiddlyWiki","userInfo":{"gitUserName":"wyleon","email":"wyleon96@gmail.com","accessToken":"ghp_up4UxEO0OMu10V9cV...","branch":"main"},"defaultGitInfo":{"email":"tiddlygit@gmail.com","gitUserName":"tidgi","branch":"main"},"logger":{}}.
fatal: couldn't find remote ref main

```

---

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.4-prerelease2

**Comment by linonetwo** [comment]
This is annoying , I'm going to make it a warning than an error. Maybe only pop a in-tw-notification

**Comment by linonetwo** [comment]
试试最新的预发版 [https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2) ， 先创建本地版，之后在配置里再开启同步，创建成功率更高。
