### ISSUE TITLE
bug: 输入框偶尔丢失焦点

### ISSUE THREAD

**Issue by LinHQ1999** [tiddly-gittly/TidGi-Desktop#176]
## Environment

Version v0.7.3.

Electron Version: 15.3.0
Node Version: 16.5.0
Chromium Version: 94.0.4606.81

OS (macOS, Windows, Linux) and Version: Windows 10 Professional

## Description:

当 tw 弹出警告框后，输入框无法继续输入。

## Steps to Reproduce:

1. 创建两个 tiddler，并不要保存。
2. 编辑其中一个 tiddler 然后保存并删除。
3. 另外一个 tiddler 无法输入。

![动画](https://user-images.githubusercontent.com/50328516/150284161-4df0da3c-6eb6-46c5-84b8-d22c90e657aa.gif)

**Comment by linonetwo** [comment]
已记录，原因是 electron/electron#19977

**Comment by linonetwo** [comment]
> 关于不能编辑文字的bug,我目前是点一下tag然后在点需要编辑的内容就可以正常编辑

**Comment by linonetwo** [comment]
之后劫持一下 alert

**Comment by Zacharia2** [comment]
我是点桌面，在点太记就可以正常编辑（让太记失去焦点在重获焦点）

**Comment by Zacharia2** [comment]
终于解决啦🎉
