### ISSUE TITLE
bug: setWikiLanguage("$:/languages/en-GB"), language "$:/languages/en-GB" in workspaceID fcea4215-9169-4e

### ISSUE THREAD

**Issue by stardustman** [tiddly-gittly/TidGi-Desktop#188]
## Environment

TidGi 0.7.4
Electron 16.0.8
darwin 20.6.0
Locale: en-US

## Description:

1. 在一台机器上已经配置好了 TidGi-Desktop，也已经创建好了在线 wiki 仓库。使用的是改名前的 TidGi-Desktop。
2. 在另外一台机器上，把 wiki 仓库直接 clone 下来，OPEN LOCAL WIKI 报的错误。

## Additional Context

```typescript
Error: setWikiLanguage("$:/languages/en-GB"), language "$:/languages/en-GB" in workspaceID fcea4215-9169-4ea8-bdfe-5192c2a54269 is too slow to update after 15000ms.
```

---

**Comment by linonetwo** [comment]
问题应该不大，就是那个 wiki没有及时启动的原因吧。

重启一下app会好吧？

你是手动clone 仓库，然后打开现有wiki文件夹？按理说一般没问题，你看看log文件夹里这个wiki的启动log吧

**Comment by stardustman** [comment]
导入线上WIKI，也报错

**Comment by linonetwo** [comment]
看看log说啥

**Comment by stardustman** [comment]
导入时能不能使用 ssh 的那个 github 仓库地址呢？

**Comment by linonetwo** [comment]
不行吧，得用 https 的。现在没问题了？看你没上传 log ，应该是解决了吧。

**Comment by stardustman** [comment]
没有，还是这个问题

**Comment by linonetwo** [comment]
上传 log啊
