### ISSUE TITLE
syncer-browser-tiddlyweb error

### ISSUE THREAD

**Issue by jabobian** [tiddly-gittly/TidGi-Desktop#189]
syncer-browser-tiddlyweb - 2022年02月11日 10:21 (计数: 8)
Sync error while processing save of '$:/StoryList': XMLHttpRequest 错误代码: 503

syncer-browser-tiddlyweb - 2022年02月11日 10:20 (计数: 2)
简要条目清单撷取错误: XMLHttpRequest 错误代码: 503

don't know how to solve this issue. Thanks!

**Comment by linonetwo** [comment]
Hi, this is due to the wiki backend being offline. Maybe you can look at the wiki's log for some clue.

**Comment by linonetwo** [comment]
Do you know how to open the log? The button is located in preference-developer

**Comment by jabobian** [comment]
I will check the log when The problem comes again.

**Comment by linonetwo** [comment]
If it doesn't presist, I can close this.
