### ISSUE TITLE
bug: can't connect to server after switch wifi

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#191]
This is because server will have different ip in different wifi.

Consider using localhost for local in-app-serving, and reverse proxy with token to allow scan QR code open in the phone. as in https://github.com/tiddly-gittly/TidGi-Desktop/projects/8#card-74037652

**Comment by linonetwo** [comment]
网络环境切换了就会这样，不管是断网还是切换网，我看看能不能搞个自动重启，这样就不用用户去操作了

**Comment by linonetwo** [comment]
或者弹框问用户要不要重启

**Comment by linonetwo** [comment]
说明现在数据是不会保存的

**Comment by linonetwo** [comment]
![截屏2022-05-11 16 06 07](https://user-images.githubusercontent.com/3746270/167857001-dfb68c07-682e-4833-a1af-de488fb221e2.png)

**Comment by linonetwo** [comment]
还是默认连 127.0.0.1 这样切换网络他也不会变化，只对有特殊需求的人开启外部访问

**Comment by linonetwo** [comment]
A user using TidGi also lost half an hour of his data (better than half a year...), because of that network connection error.

![](https://user-images.githubusercontent.com/3746270/168197568-23bbe87a-b3ca-4cbb-aaf4-917436d80c2d.png)

This is because TidGi starts a nodejs wiki, and listen on 0.0.0.0 ,and the browserview open the wiki on 192.168.xx.xx , and if you switch wifi, the 192.168.xx.xx will not be accessible, you have to access it from 10.xx.xx.xx

**Comment by linonetwo** [comment]
see also Jermolene/TiddlyWiki5#5952

**Comment by linonetwo** [comment]
这可不能想当然

**Comment by linonetwo** [comment]
@e792a8 通过配置来切换。你评论是打算来PR改吗

**Comment by e792a8** [comment]
没有PR，今天刚从知乎找过来。我一看连的是个IP就猜到有这问题。等我有空研究下
