### ISSUE TITLE
能不能打包一个.appimage呢？

### ISSUE THREAD

**Issue by TzhuZaPlan** [tiddly-gittly/TidGi-Desktop#203]
自己使用的是Arch，想要使用TidGi就只能使用debtap进行转，较为麻烦，希望能出一个官方的appimage版本

**Comment by linonetwo** [comment]
https://github.com/electron-userland/electron-forge/issues/26

flatpack 也是，好像没人维护 electron forge 它们的打包器了。感觉如果没人去修的话，electron forge 官方已经不管了。

**Comment by linonetwo** [comment]
https://github.com/electron-userland/electron-forge/issues/1792

**Comment by linonetwo** [comment]
snap 也不行 electron-userland/electron-forge#1652
