### ISSUE TITLE
bug: Perplexed progress of the installation

### ISSUE THREAD

**Issue by likuan61** [tiddly-gittly/TidGi-Desktop#206]
## Environment

TG Version v

Electron Version:

Node Version:

Chromium Version: MS Eage

OS (macOS, Windows, Linux) and Version: Windows 10

## Description:

During the process of installation, the application has been started while the process of installation is still shown in the process, namely the animation of the installation is being shown.

The log files are as follows:

## Additional Context

[L__Apps_Tiddlywiki_IS_Std.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/8242198/L__Apps_Tiddlywiki_IS_Std.log)
[TidGi-2022-03-14.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/8242199/TidGi-2022-03-14.log)

**Comment by linonetwo** [comment]
最新的 msi 安装器应该没问题了，exe 安装器不大可控，只能顺其自然了。
