### ISSUE TITLE
feature: 安装包自定义安装路径。

### ISSUE THREAD

**Issue by tn-072** [tiddly-gittly/TidGi-Desktop#207]
## Environment

TG Version v

Electron Version:

Node Version:

Chromium Version:

OS (macOS, Windows, Linux) and Version:

## Description:

希望安装包可以自定义安装路径，而不是直接存进C盘appdata中，这样的设计对C盘分区较小的用户不太友善。（尤其是当他需要安装、更新VS等大型软件时）

**Comment by linonetwo** [comment]
之后看看咋改，这个得看 Electron forge 社区有没有方案，之前安装包都是直接用社区方案。

还顺便看看能不能搞出 win32 版的

**Comment by tn-072** [comment]
谢谢了。原来是Electron的问题，现在明白为什么XMind、Atom都是直接安装无法自定义安装路径了。
