### ISSUE TITLE
bug: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。 initWikiGitTransaction failed, E-3 failed to config git 

### ISSUE THREAD

**Issue by luochongyin** [tiddly-gittly/TidGi-Desktop#210]
## Environment

TidGi 0.7.5
Electron 17.0.1
win32 10.0.22000
Locale: zh-CN

**Comment by luochongyin** [comment]
> ## Environment
> TidGi 0.7.5 Electron 17.0.1 win32 10.0.22000 Locale: zh-CN
> 
> ## Description:
> ## Steps to Reproduce:
> ## Additional Context
> ```ts
> Error: E-1 新笔记仓库所用的模板复制失败或者笔记仓库的git初始化失败，这应该是个bug。

**Comment by linonetwo** [comment]
## Steps to Reproduce？

**Comment by linonetwo** [comment]
log 看看
