### ISSUE TITLE
bug:  在TIdGi中删除某一条目，实际不会同步到github上去

### ISSUE THREAD

**Issue by Harold-lkk** [tiddly-gittly/TidGi-Desktop#217]
### Environment

Mac M1 、Ubuntu18.04

### Description 描述

bug:  在TIdGi中删除某一条目，实际不会同步到github上去

### Steps to Reproduce 复现方式

在软件中直接删除某一条目后立马同步，在github的repo中仍然存在该条目

**Comment by linonetwo** [comment]
[https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.7-prerelease2](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.7-prerelease2) 修了
