### ISSUE TITLE
bug: listen EACCES: permission denied 0.0.0.0:5212

### ISSUE THREAD

**Issue by kiyurei** [tiddly-gittly/TidGi-Desktop#219]
## Environment

TidGi 0.7.6
Electron 18.0.1
win32 10.0.19042
Locale: zh-CN

## Additional Context

```typescript
Error: listen EACCES: permission denied 0.0.0.0:5212
```

---

[D__Desktop_wiki_wiki.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/8438579/D__Desktop_wiki_wiki.log)
[TidGi-2022-04-07.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/8438580/TidGi-2022-04-07.log)

**Comment by kiyurei** [comment]
![TidGi_7QtRh7UdBJ](https://user-images.githubusercontent.com/101028325/162096779-87c885ab-bce9-41b4-9818-17a18b686abf.png)
![TidGi_n8vl2xA7BA](https://user-images.githubusercontent.com/101028325/162096784-af50f674-d1f2-4067-93d9-8b5b5aa5f411.png)

**Comment by linonetwo** [comment]
我没咋用 windows，搜了下好像是杀毒软件的问题 https://stackoverflow.com/questions/59428844/listen-eacces-permission-denied-in-windows

**Comment by linonetwo** [comment]
或者是装好更新重启下就好了，先试试看吧
