### ISSUE TITLE
bug: 暗色模式文字颜色未改变

### ISSUE THREAD

**Issue by inkydragon** [tiddly-gittly/TidGi-Desktop#222]
### Environment

全新安装，首次打开
- TidGi (win32) Version v0.7.6.
- Electron Version: 18.0.1
- Node Version: 16.13.2
- Chromium Version: 100.0.4896.60

### Description 描述

暗色模式下，侧边栏文字、图标颜色未改变，难以辨认。

![image](https://user-images.githubusercontent.com/5158738/162604488-a5c8ed4a-130f-494f-8c93-b5390bce5cdf.png)

### Steps to Reproduce 复现方式

主题色设置为 `Dark`

### Additional Context

另外 ISSUE_TEMPLATE 中复制 ENV 信息的指引不太准确了

> You can copy this from right click context menu → More → About

目前应该是："TidGi\About" 然后复制

![image](https://user-images.githubusercontent.com/5158738/162604954-f986866e-3f72-4b1b-9843-993730266fa9.png)

_No response_

**Comment by linonetwo** [comment]
[https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.7-prerelease3](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.7-prerelease3)

中午支持了一下
