### ISSUE TITLE
feature: pandoc export

### ISSUE THREAD

**Issue by anthrolisp** [tiddly-gittly/TidGi-Desktop#232]
### Description 描述

This is an incredible project! Thank you!
It would be incredible if there was an ability to export to DOCX or PDF either natively or through some kind of plugin of the content of a tiddler. Even more incredible would being able to export a list a of them as one document. 
Thank you again!

**Comment by linonetwo** [comment]
You can try this to export PDF
<img width="169" alt="截屏2022-05-07 21 47 31" src="https://user-images.githubusercontent.com/3746270/167257137-bdb021c2-88ce-4573-9f72-b6ca8ccf2c05.png">

In the wiki menu on the menubar.

**Comment by linonetwo** [comment]
Is this sufficient for you?
