### ISSUE TITLE
bug: 删除一个工作区后，重建时完全无法顺利生成，一直是java插件错误，首页只剩标题。

### ISSUE THREAD

**Issue by guangfengzhuanhui** [tiddly-gittly/TidGi-Desktop#236]
### Environment 环境信息

TidGi (win32)
Version v0.7.7.

Electron Version: 18.2.0
Node Version: 16.13.2
Chromium Version: 100.0.4896.143

### Description 描述

![0b3a69deb9a84f0c910763d45ecffa96](https://user-images.githubusercontent.com/97065917/169282121-9793e7f6-3460-409d-bb70-dd0c4896eb86.png)
![download](https://user-images.githubusercontent.com/97065917/169282151-cbbaec7d-ba1f-424c-9bde-862a566faff6.gif)

我对github究竟怎么操作确实还不是太了解，最开始创了一个可以同步的，因为有问题改起来挺麻烦就干脆直接删了储存区，之后就每次重建都有问题。
一开始windows创建，然后导入mac用了两天，就出问题了。

### Steps to Reproduce 复现方式

{"homePath":"C:\\Users\\me\\Documents\\save\\Tddly","level":"debug","message":"wiki message","payload":{"message":" syncer-server-filesystem: Dispatching 'save' task: $:/language \n","type":"stdout"},"timestamp":"2022-05-19T11:19:01.642Z","type":"result","uid":2,"worker":"NodeJSWiki"}
{"level":"debug","message":"throttledDidFinishedLoad() workspace.id: 81f6d5f9-533a-4207-93a7-a84aad3bc339, now workspaceViewService.realignActiveWorkspace() then set isLoading to false","timestamp":"2022-05-19T11:19:02.409Z"}
{"level":"debug","message":"realignActiveWorkspaceView() activeWorkspace.id: 81f6d5f9-533a-4207-93a7-a84aad3bc339","timestamp":"2022-05-19T11:19:02.410Z"}
{"level":"info","message":"realignActiveWorkspaceView: id 81f6d5f9-533a-4207-93a7-a84aad3bc339 mainWindow: true menuBarWindow: false","timestamp":"2022-05-19T11:19:02.410Z"}
{"isLoading":false,"level":"debug","message":"updateMetaData(81f6d5f9-533a-4207-93a7-a84aad3bc339)","timestamp":"2022-05-19T11:19:02.410Z"}
{"homePath":"C:\\Users\\me\\Documents\\save\\Tddly","level":"debug","message":"wiki message","payload":{"message":" syncer-server-filesystem: Dispatching 'save' task: GettingStarted \n","type":"stdout"},"timestamp":"2022-05-19T11:19:15.760Z","type":"result","uid":2,"worker":"NodeJSWiki"}

**Comment by linonetwo** [comment]
你装的是 ia32 版的还是 x64 版的呀？

**Comment by linonetwo** [comment]
右键打开开发者工具，，截一下报错。那里会显示这个报错来自什么插件。

还有你是怎么删除的？有没有删除干净呀？还有你新建是不是新建到了之前的文件夹里嵌套了，最好新建在桌面新建一个文件夹来放你的新工作区。

**Comment by guangfengzhuanhui** [comment]
这个开发工具吗？
![image](https://user-images.githubusercontent.com/97065917/169404872-5e4c4d77-4507-456c-8af0-9ba64aabc527.png)

我是移除工作区和删掉github的储存库，win和mac应该下的都是写了64的。
我新建的位置不一样，名字也不一样，看有说在线库有可能直接加载有问题，我是先建了本地库。

**Comment by linonetwo** [comment]
@guangfengzhuanhui 看下 console tab ，里面有详细的报错信息，还说了他是哪个插件的报错。

看你现在这个新的报错跟之前的不是同一个呀。新的这个应该是所见其所得编辑器的报错，升级一下插件就好了。你也可以加QQ群来讨论，这个问题在新版插件已经修复了。

**Comment by linonetwo** [comment]
@guangfengzhuanhui 看下 console tab ，里面有详细的报错信息，还说了他是哪个插件的报错。

看你现在这个新的报错跟之前的不是同一个呀。新的这个应该是所见其所得编辑器的报错，升级一下插件就好了。你也可以加QQ群来讨论，这个问题在新版插件已经修复了。
