### ISSUE TITLE
feature: [新功能请求]可以打包二进制或者AppImage吗

### ISSUE THREAD

**Issue by a15355447898a** [tiddly-gittly/TidGi-Desktop#242]
### Description 描述

安装包提供AppImage或者二进制版本以满足其他linux发行版的用户

**Comment by linonetwo** [comment]
不大行啊， https://github.com/tiddly-gittly/TidGi-Desktop/issues/203 之前没成功，有勇者来试试吗？

**Comment by oeyoews** [comment]
https://github.com/oeyoews/neotw-app/blob/65843bdf3ea496d47bd45d17e364ec3f73079bd0/forge.config.js#L43  可以用这个

**Comment by linonetwo** [comment]
@oeyoews 那你之前搞的 makerfile 就不用了吗？

**Comment by oeyoews** [comment]
这个不是更简洁方便吗， 我大致看了下这个包， 是借助appimagekit进行构建的， 专门为electron-forge写的npm包 @linonetwo

**Comment by linonetwo** [comment]
不行，会失败

[https://github.com/tiddly-gittly/TidGi-Desktop/actions/runs/3508842799/jobs/5877536630](https://github.com/tiddly-gittly/TidGi-Desktop/actions/runs/3508842799/jobs/5877536630)

先去掉了，你们有空可以折腾看看 7236aa9

**Comment by linonetwo** [comment]
不行，会失败

[https://github.com/tiddly-gittly/TidGi-Desktop/actions/runs/3508842799/jobs/5877536630](https://github.com/tiddly-gittly/TidGi-Desktop/actions/runs/3508842799/jobs/5877536630)

先去掉了，你们有空可以折腾看看 7236aa9

**Comment by SpacingBat3** [comment]
> 不行，会失败
> 
> https://github.com/tiddly-gittly/TidGi-Desktop/actions/runs/3508842799/jobs/5877536630
>
> 先去掉了，你们有空可以折腾看看 https://github.com/tiddly-gittly/TidGi-Desktop/commit/7236aa975906b129e683ae3d0bc534dda149e0cd

@linonetwo Hi, AppImage maker dev here.

The current release of Forge and my maker should both provide better logging (no more printing `[object Object]` on Forge side, more precise error messages and handling `mksquashfs` error codes on my side) and introduce fixes to some common bugs. Now it is more likely it will work fine and if not you should get some indication what you need to change in your configuration (or if it is still some kind of bug on my side – information what I might need to fix).

There's also a documentation for configuration options (based on currently-in-development version of maker in `master` branch) available [here](https://spacingbat3.github.io/ReForged/interfaces/MakerAppImageConfigOptions.html).

Hope this helps 😄️.

**Comment by linonetwo** [comment]
Thank you @SpacingBat3 , https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.15-prerelease3-fix1 it seems to work!

@oeyoews @a15355447898a Please try out.
