### ISSUE TITLE
bug: E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。 C:\Users\13662\Desktop\TiddlyWiki\wiki listen EACCES: p

### ISSUE THREAD

**Issue by lgf-136** [tiddly-gittly/TidGi-Desktop#243]
## Environment

TidGi 0.7.7
Electron 18.2.0
win32 6.2.9200
Locale: en-US

## Additional Context

```typescript
Error: E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。 C:\Users\13662\Desktop\TiddlyWiki\wiki listen EACCES: permission denied 0.0.0.0:5212
```

---

**Comment by linonetwo** [comment]
是不是防火墙没点同意

**Comment by linonetwo** [comment]
换个端口就好，之后我加个自动换端口

**Comment by oeyoews** [comment]
port finder 这个包我记得可以自动查找空闲的端口

**Comment by linonetwo** [comment]
这个我最近应该没空改，主要是我自己没遇到过，低优跟进

**Comment by linonetwo** [comment]
https://github.com/unjs/get-port-please 这个更好

**Comment by linonetwo** [comment]
这个类似 https://github.com/tiddly-gittly/TidGi-Desktop/issues/288

我猜都是因为开了 vpn 全局才这样
