### ISSUE TITLE
bug: setWikiLanguage("$:/languages/zh-Hans"), language "$:/languages/zh-Hans" in workspaceID aef894fd-ad2

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#249]
## Environment

TidGi 0.7.7
Electron 18.2.0
win32 10.0.19044
Locale: zh-CN

## Description:

[C__Users_Mxun_Desktop_TiddlyWiki-CPL.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/9136383/C__Users_Mxun_Desktop_TiddlyWiki-CPL.log)
[TidGi-2022-07-19.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/9136385/TidGi-2022-07-19.log)

## Steps to Reproduce:

fork仓库TiddlyWiki-CPL并克隆到本地，导入到TidGi时发生的错误，无法导入。

## Additional Context

```typescript
Error: setWikiLanguage("$:/languages/zh-Hans"), language "$:/languages/zh-Hans" in workspaceID aef894fd-ad2e-4a75-b4f4-294f649050cb is too slow to update after 15000ms.
```

---

![image](https://user-images.githubusercontent.com/32425955/179637343-adfd7b31-df6a-4b52-98fb-32e735cfa308.png)

**Comment by linonetwo** [comment]
其实已经导入成功了，关闭这个窗口重启一下app应该是可以用的吧

**Comment by Zacharia2** [comment]
嗯嗯，似乎是这样的🙂
