### ISSUE TITLE
bug: 太记在输入中的问题

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#256]
### Environment 环境信息

TidGi (win32)
Version v0.7.7.

Electron Version: 18.2.0
Node Version: 16.13.2
Chromium Version: 100.0.4896.143

### Description 描述

在直接写的过程中,出现了鼠标移动不过去的问题，一般有这个问题的时候就是旁边会显示一个滚动条,然后就会有问题了

### Steps to Reproduce 复现方式

![NV)Q9FH_A2{XVO2AMQAW`MM](https://user-images.githubusercontent.com/32425955/181783866-47e56d35-869c-4f37-b33b-ad4f6a163eb6.jpg)
大概类似这种，当时就是我想在"简要之"旁边补充一些内容,但鼠标一直移动不过去。

比如现在.你看光标一直停在"说"字上面，无法移动。

![KL6F_`F8 V KT)3D05 8HG](https://user-images.githubusercontent.com/32425955/181784999-766de711-f523-4050-a3e7-a52284edaea8.jpg)

现在这个条目是卡死了，也能编辑,就是鼠标移动不方便。（经过测试，似乎不是输入法的问题）

**Comment by Zacharia2** [comment]
群友机杼的问题，已在中交流

**Comment by linonetwo** [comment]
机杼  是指啥
