### ISSUE TITLE
feature: support appimge(DONE)

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TidGi-Desktop#263]
### Description 描述

details: https://oeyoew.fun/#tidgi2appimage

**Comment by linonetwo** [comment]
这个转换稳定的话，我可以在action发布之前这样转换一下，虽然没有直接打 appimg 那么直接合理，但是毕竟能用对吧

**Comment by linonetwo** [comment]
谢了啊

**Comment by oeyoews** [comment]
![image](https://user-images.githubusercontent.com/72405338/187030892-160a4389-25a9-4a48-892b-55d047ca8655.png)

我记得tidgi是内置了chromium的吧， 果然是内存大户， tauri听说不错， 好像是使用本地浏览器内核

**Comment by linonetwo** [comment]
我还没加上呢，有时间得在 github action 里配一下

**Comment by linonetwo** [comment]
tauri 如果用户的浏览器出bug了找我咋办，那可烦不胜烦了，还是 Electron 发挥稳定，省事儿，毕竟没有专职客服

**Comment by oeyoews** [comment]
所以有人说， Tauri好像在开历史的倒车

**Comment by linonetwo** [comment]
wget https://github.com/simoniz0r/deb2appimage/releases/download/v0.0.5/deb2appimage-0.0.5-x86_64.AppImage -O deb2appimage.appimag

```
chmod +x ./deb2appimage.appimage

./deb2appimage.appimage -j ./tidgi.json
```

**Comment by linonetwo** [comment]
是这么搞吗？你有空可以往 .github/workflows/release.yml 里加一下，以便自动发布

**Comment by oeyoews** [comment]
electron-forge 生成的包都是放在了out/make 目录吗

**Comment by linonetwo** [comment]
这个，我只记得在 out 里…你本地构建一下试试呗

**Comment by oeyoews** [comment]
有时间我装下依赖再试试看，感觉也没多少人会用appimage了吧，毕竟ubuntu系，和arch都已经支持了

**Comment by oeyoews** [comment]
> 这个，我只记得在 out 里…你本地构建一下试试呗

装依赖报错

```
✔ Checking your system
⠋ Preparing to Package Application for arch: x64ten Completed in 5ms
An unhandled rejection has occurred inside Forge:
Error: Could not find any Electron packages in devDependencies

Electron Forge was terminated. Location:
{}
```

**Comment by linonetwo** [comment]
你得先确保 node 版本和 。nvmrc 里的一致，然后在项目根目录去执行 npm i 以及 build 相关的 npm 脚本

**Comment by linonetwo** [comment]
删除 nodemodules 重装依赖或许可以解决，可能是 electron 没安装成功，用 https://blog.csdn.net/Aria_Miazzy/article/details/106187406 安装

**Comment by linonetwo** [comment]
之后如果还打算自己写脚本的话，可以参考 scripts/buildAppImage.mjs d16813c
