### ISSUE TITLE
希望新增多窗口模式 

### ISSUE THREAD

**Issue by yuholqjn** [tiddly-gittly/TidGi-Desktop#267]
### Description 描述

希望打开tidgi之后，再次点击图标，还能打开一个。
实现类似浏览器的效果。

**Comment by linonetwo** [comment]
好像多个浏览器标签页之间会共用「打开的条目列表」，所以不知道能不能做到这样啊，你调研一下？可以用浏览器试试

**Comment by linonetwo** [comment]
下个版本要支持了，可以点watch关注一下
