### ISSUE TITLE
feature: change default username

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/TidGi-Desktop#269]
### Description 描述

![image](https://user-images.githubusercontent.com/72405338/187407248-32ef09bc-08b2-4de6-a2fc-01bfde0e9d49.png)

建议将默认的username置空， 如果用户在使用`TidgiUser`一段时间后又修改了username, 会出现两个用户名, 或者也可以将默认的用户名设置为本机电脑的用户名更为妥当

**Comment by linonetwo** [comment]
也有道理，不过不知道有没有包能获取用户名

**Comment by linonetwo** [comment]
或者改为在app刚打开时展示个框让用户填写吧
