### ISSUE TITLE
bug: memory usage escalating when import big pdf file larger than 100MB

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#270]
### Description 描述

memory usage escalating above 4GB from 500MB when import big pdf file larger than 100MB, is there memory leaking? And the application fall into an frozen status. I can't use it at all until restarting it after the big pdf file is deleted from local filesystem.
I would fail to use TidGi as a E-book library if it can't handle big files. (But it is tested that the Node.js edition  can works well.)
Would you plan to fix this performance bug recently?

![image](https://user-images.githubusercontent.com/45555611/191248392-87814fcd-0cd7-4db4-9c06-ec7d27a7ab55.png)

### Steps to Reproduce 复现方式

 import big pdf file larger than 100MB

**Comment by linonetwo** [comment]
I did tried importing some 50M PDF and didn't suffered from this. Can you try importing PDF inside the browser (right click on workspace icon , select edit workspace, and there you can see the URL of this wiki, you can open it in the browser).

If this happened in the browser too, then it is the tw's bug, otherwise it's TidGi's bug.

**Comment by linonetwo** [comment]
And you actually can't read PDF in TidGi, not like https://github.com/burtonator/polar-bookshelf .

I personally use system's native PDF reader, and only take note in the TiddlyWiki. But I also drag the PDF to tidgi to sync it to the github, not experience the bug like you have.

**Comment by heavenkiller2018** [comment]
UI usually frozens and nothing can be clicked while I open the big PDF(about 180MB) file's tiddler with the Edge browser.  So it's a bug of TiddlyWiki. What a shallow bug which hasn't been committed to TiddlyWiki formerly?

![image](https://user-images.githubusercontent.com/45555611/191376761-400ceb21-2ad7-4cfa-987e-cf518affd722.png)

![image](https://user-images.githubusercontent.com/45555611/191376883-1c024d15-3c99-42b3-83cd-c9c0fae39cc5.png)

**Comment by heavenkiller2018** [comment]
I originally planned to store some file(such as .md,.pdf,.mp3) in TidGi and then open it with os native application. For example, sometimes I need to open and edit a tiddler of markdown type with Typro becauseof it's peerless experience. 

I have noted in the description of plugin `open-in-external-app`:
```
Note that if you use this to open a .tid or .md file, and edit it, things won't change in the wiki, because the tiddlywiki currently doesn't reload changed files from the disk.
```

but in fact, while the .md file opened through `open-in-external-app` is edited and saved in Typro,  it's synced in local filesystem indeedly. The problem is that the changes cann't be reflected immediately, even though click `Get latest change from the server` in toolbar manually, unless I restart the TidGit app. Why there are no effects of `Get latest change from the server` under the related file has changed? The experience would be wonderful if we can edit and save .md files in Typro directly with no need of restarting the app! expect your solutions sincerely!

**Comment by heavenkiller2018** [comment]
an simple workaround is to only restart service instead of restarting the whole app

**Comment by linonetwo** [comment]
yes, right click and select "reload service". Don't forget to change language.

**Comment by linonetwo** [comment]
You can report that bug to tiddlywiki with a github repo to reproduce this behavior.

**Comment by linonetwo** [comment]
@heavenkiller2018 did you report this to tiddlywiki?
