### ISSUE TITLE
bug: UI problem about plugins:Opened Tiddlers Bar, Menu Bar, inverse-link-and-folder

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#271]
### Description 描述

UI problem about plugins:Opened Tiddlers Bar, Menu Bar, inverse-link-and-folder

**Opened Tiddlers Bar**

without automatic wrapping as storytab plugin if there are too many tabs to place them in one line so that opened tiddlers can't appear fully

**Menu Bar**
Related Contents don't appear like then Native Node.js TiddlyWiki  when plugin `Menu Bar` is enabled 

**UI differences between TidGi and Native Node.js TiddlyWiki:**

Native Node.js TiddlyWiki:
![image](https://user-images.githubusercontent.com/45555611/191388147-39d40412-80d7-49f3-b997-785ff021a10c.png)

 TidGi 
![image](https://user-images.githubusercontent.com/45555611/191388391-45fc66f1-e4b9-4797-b012-a90e1064b506.png)

**inverse-link-and-folder**

tiddler tree like this:
```
test1
  -- test2
    -- test3
```

in tiddler test1 page, when I move the mouse to hover over the tag `test2` at the bottom, the tag `test3` appears in the form of tooltip, but as soon as I am going move to it, the pop tooltip disappear immediately so it's impossible to click on tag `test3`

![image](https://user-images.githubusercontent.com/45555611/191387985-dc5e31e5-90c2-4564-b4a0-26018500f189.png)

### Steps to Reproduce 复现方式

.

**Comment by linonetwo** [comment]
These are about plugins, you can choose to use official tabs plugin. And my tabs plugin can scroll by shift+scroll .

Appear plugin seem to have some bug, but I may not have time to fix plugins now.
