### ISSUE TITLE
bug: Uncaught TypeError: Cannot read properties of undefined (reading 'attach') when editing a special tiddler

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#272]
### Description 描述

When I edit a special tiddler `Images`, a internal error occurs. Other tiddlers are nornam without such errors.

![image](https://user-images.githubusercontent.com/45555611/191405001-81f09adf-bb0d-445f-9cf7-54686955d798.png)

why? By the way ,where to check logs and set the level of log?

### Steps to Reproduce 复现方式

edit a special tiddler `Images`

**Comment by linonetwo** [comment]
What is "Images" tiddler? I don't have that.


<img width="894" alt="截屏2022-09-21 14 50 18" src="https://user-images.githubusercontent.com/3746270/191434284-aa71e1a7-dd8b-4bae-96e0-b33bcf3553fd.png">

Log ↑

**Comment by heavenkiller2018** [comment]
the "Images" tiddler is just a plain tiddler withou any points of difference. I doubt some plugin is related to this specific tiddler named 'Images' to generate such error. But what is the detail of error "reading 'attach'"

![image](https://user-images.githubusercontent.com/45555611/191487370-c05e3c0f-63c7-42fe-ab21-f1d9987aff85.png)

**Comment by linonetwo** [comment]
![](https://user-images.githubusercontent.com/3746270/191493747-972ce05b-c2f6-4a3f-8dc8-d33d4ba07d5f.png)

due to this button, WYSIWYG editor didn't adapt the element in that tiddler. Try click on this button again, or delete "wysiwyg" field in this tiddler (using old edit mode)

**Comment by heavenkiller2018** [comment]
thanks, it's resolved!
