### ISSUE TITLE
bug: E-8 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug -100 ERR_CONNECTION_CLOSED https://www.bilibili.com/video/BV

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#278]
## Environment

TidGi 0.7.9
Electron 20.2.0
win32 10.0.22000
Locale: zh-CN

## Additional Context

```typescript
E-8 工作区加载失败错误: E-8 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug -100 ERR_CONNECTION_CLOSED https://www.bilibili.com/video/BV1BJ411r7TE/?spm_id_from=autoNext
    at Fa.initializeWorkspaceView (C:\Users\34656\AppData\Local\TidGi\app-0.7.9\resources\app.asar\.webpack\main\index.js:2:1744732)
    at C:\Users\34656\AppData\Local\TidGi\app-0.7.9\resources\app.asar\.webpack\main\index.js:2:1742022
```

---

![RM4AR1OU1S81(QLEVB%NT~4](https://user-images.githubusercontent.com/109711900/194485296-c2a32a38-3f19-468c-bc2c-81eb5b1ec7ac.png)

没有别的截图了。因为我回来重新打开就是这样的了，然后我就点提交问题了。

{"type":"running","uid":3,"resultType":"observable"}
{"type":"result","uid":3,"payload":{"type":"control","actions":"tw-start"}}
{"type":"result","uid":3,"payload":{"type":"stdout","message":" syncer-server-filesystem: Dispatching 'save' task: $:/StoryList \n"}}
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList 
{"type":"result","uid":3,"payload":{"type":"stdout","message":"Serving on http://0.0.0.0:5215\n"}}
Serving on http://0.0.0.0:5215
{"type":"result","uid":3,"payload":{"type":"stdout","message":"(press ctrl-C to exit)\n"}}
(press ctrl-C to exit)
{"type":"result","uid":3,"payload":{"type":"control","actions":"tw-booted","message":"Tiddlywiki booted at http://0.0.0.0:5215 (webview uri ip may be different, being getLocalHostUrlWithActualIP()) with args --listen anon-username=马不前 port=5215 host=0.0.0.0 root-tiddler=$:/core/save/lazy-images"}}

**Comment by dongrentianyu** [comment]
![image](https://user-images.githubusercontent.com/109711900/194495835-ba990fd8-7b81-48b1-af1a-fe9b3962d609.png)
移除之后重新导入了一下，竟然找回了。太记真的太好了。

**Comment by dongrentianyu** [comment]
<iframe src='https://www.bilibili.com/video/BV1At4y1P7Vt/?spm_id_from=333.851.b_7265636f6d6d656e64.6' frameborder="0" width="1024"; height="600"></iframe>

大概这是我当时的代码。

<img width="424" alt="image" src="https://user-images.githubusercontent.com/109711900/194517818-0ac1d567-7235-404e-a252-c2c36ff7fb5f.png">

因为我是从这里复制视频网址的。

然后就报错了。

**Comment by dongrentianyu** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/194518384-200a1548-245a-4f43-8de2-939a982430ff.png">
所以展示出来的就是b站整个网站，而不是像官方文档里的那样是一个视频。

**Comment by linonetwo** [comment]
除了把 iframe 嵌入笔记里以外，是怎么让整个页面都变成b站的？是点了什么链接吗？

**Comment by dongrentianyu** [comment]
找到这个了。我刚才使用设拉子插件，想做一个徽章，里面有一个跳转链接。

<a href="https://kookma.github.io/TW-Shiraz/" class="badge badge-primary">Primary</a>

刚才我使用的格式是这样的。在用tiddlywiki desktop上，点击会跳转到edge浏览器里打开。而在太记里，则会在太记里打开。

<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/210162031-7c9ed263-877e-4376-ab55-33f270ac7aac.png">

github desktop回退后，刷新重启都没有用。只能是先移除文件夹，再重新添加一次，才能回到原来的模样。

具体原因我也不清楚。

**Comment by dongrentianyu** [comment]
`<a href="https://kookma.github.io/TW-Shiraz/" class="badge badge-primary">Primary</a>`

上面的代码是这样的，忘记用代码框起来了

**Comment by dongrentianyu** [comment]
`<<dbadge 笔记应用 "[[TGNote|https://github.com/tiddly-gittly/TiddlyGit-Desktop]]" info>> <<dbadge 部署 "[[Github Actions|https://github.com/tiddly-gittly/TiddlyWiki-Chinese-Tutorial/actions]]" success>> <<dbadge 双向链接 "[[支持|反向链接]]" "danger">>`

`<a href="https://app.netlify.com/sites/tw-cn/deploys">
<$image source="https://api.netlify.com/api/v1/badges/2d87784e-fe3b-47a2-ae73-7a2f266f74a8/deploy-status" />
</a>`

 我去太微中文社区找了两个例子，发现第1个示例是正常跳转到edge浏览器来的。另一个还是老样子。直接在里面就打开了。

<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/210162462-d58af566-8ce8-4753-96e5-03c979f43328.png">

我在设拉子上找了一圈，好像只有第1种方式会跳转到外部，其他方式都是直接在内部跳转的。单文件版本可能不支持这种属性，所以没有出现这种问题。

**Comment by linonetwo** [comment]
看起来是，那我有空改成外部跳转的
