### ISSUE TITLE
feature: support/ install for linux

### ISSUE THREAD

**Issue by anthrolisp** [tiddly-gittly/TidGi-Desktop#289]
### Description 描述

Is there support for installing TidGi on non-arch Linux systems? Thank you!

**Comment by linonetwo** [comment]
Maybe use [TidGi-0.7.9-1.x86\_64.rpm ](https://github.com/tiddly-gittly/TidGi-Desktop/releases/download/v0.7.9/TidGi-0.7.9-1.x86_64.rpm) ?

**Comment by linonetwo** [comment]
No response
