### ISSUE TITLE
feature: 修改右键样式，避免功能重复

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#307]
### Description 描述

提个小小的建议，在隐藏侧边栏的情况下，右键点击会显示工作区和打开工作区，需要把鼠标移动到具体的工作区里，才会有本地git备份或者用浏览器打开等操作。

其实可以省掉一个工作区，然后把那些操作放在当前工作区上面，这样虽然有点长，但就可以隐藏侧边栏了。不然每次用可视化git工具打开，要么就是右键点工作区，再移动到当前工作区，再打开。要么就是侧边栏右键点击。感觉整个流程可以优化一下。

### Additional Context 额外上下文

<img width="301" alt="image" src="https://user-images.githubusercontent.com/109711900/203454334-ebfeaaef-d245-4a8e-a105-7d2bd0a726fd.png">

<img width="428" alt="image" src="https://user-images.githubusercontent.com/109711900/203454397-1db3a2d6-e119-4d23-8220-4ae363aa156b.png">

**Comment by linonetwo** [comment]
搞了个这样的

![](https://user-images.githubusercontent.com/3746270/203517732-f3d53f35-4c9f-4f18-90a3-66eff6c9e83f.png)
