### ISSUE TITLE
feature: 建议恢复Apple M1芯片版本

### ISSUE THREAD

**Issue by xavierchen2021** [tiddly-gittly/TidGi-Desktop#309]
### Description 描述

之前报告过M1版本的无法运行，后来发现应该是签名的问题，大概率使用 这个命令 sudo xattr -r -d com.apple.quarantine 对应用重签名就可以正常使用了

**Comment by linonetwo** [comment]
com.apple.quarantine 是啥啊

**Comment by linonetwo** [comment]
目前的版本应该是通用的吧，m1 m2也可以使用

**Comment by xavierchen2021** [comment]
> 

是可以用，不过是用 Rosetta 运行的

**Comment by xavierchen2021** [comment]
> com.apple.quarantine 是啥啊

这个是用户自签名工具包 貌似

**Comment by linonetwo** [comment]
[https://www.zhihu.com/question/431722091/answer/1592339574](https://www.zhihu.com/question/431722091/answer/1592339574) 类似这个吗

**Comment by linonetwo** [comment]
我等等发个包你试试

**Comment by xavierchen2021** [comment]
> 我等等发个包你试试

是的，类似，都是签名的问题，好的，可以

**Comment by linonetwo** [comment]
[https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2) 试试

**Comment by xavierchen2021** [comment]
> https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.12-prerelease2 试试

使用上面的命令自签名后就可以正常使用了，启动速度比x64快

**Comment by linonetwo** [comment]
好，感谢测试，下次发布我带上这个

**Comment by linonetwo** [comment]
你还需要自己运行一遍自签名吗？我已经在构建脚本里运行过一次了，你还要自己再运行一次吗？

**Comment by linonetwo** [comment]
现在理论上应该直接下下来就能用了吧。

**Comment by xavierchen2021** [comment]
> 现在理论上应该直接下下来就能用了吧。

不行的，我之前用的其他用electron打包的m1的程序都需要自己再签一遍，苹果的这个签名在electron上具体啥问题我也不清楚，总之用户需要自己签名一次，才能正常使用，更新的话，还需要再签

**Comment by linonetwo** [comment]
那好吧，那看来只能在使用说明里面告诉用户这样的用法了。

**Comment by xavierchen2021** [comment]
> 那好吧，那看来只能在使用说明里面告诉用户这样的用法了。

嗯嗯，是的呀，不过就安装后签名一次，也还好，关键是我这一天用下来，感觉arm版的要流畅好多

**Comment by Irischen0301** [comment]
这个方法的确可以，需要自己运行一次。
