### ISSUE TITLE
feature: a plugin able to execute jupyter notebook files on TidGi

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#312]
### Description 描述

it would be awesome if jupyter notebook can be replaced with TidGi  more or less, just like ZX which has been achieved by plugin `linonetwo/zx-script`. It may prevail TidGi largely!

**Comment by linonetwo** [comment]
Yes, but I have no time for zx plugin recently I think...Hope someone can propose its UI, feature, and hopefully the PR.
