### ISSUE TITLE
bug: kookma的todolist的插件所生成的intersititial-ui里面样式被覆盖

### ISSUE THREAD

**Issue by YrracOwl** [tiddly-gittly/TidGi-Desktop#313]
### Environment 环境信息

TidGi (win32)
Version v0.7.12-prerelease2.

Electron Version: 21.3.0
Node Version: 16.16.0
Chromium Version: 106.0.5249.181

### Description 描述

todolist插件在intersititial-ui中插入item，观察到每一个item上的**时间**产生了换行，而在todolist的[官方示例](https://kookma.github.io/TW-Todolist/#18th%20November%202021)中没有。

### Steps to Reproduce 复现方式

新建条目，在正文插入

```
<<interstitial-ui base:"$(currentTiddler)$" caption:" ">>
```

然后随便输入一些字符，回车。

### Additional Context 额外上下文

检查元素定位到是`$:/plugins/kookma/todolist/styles/main.css`中的`.kk-todolist-row .kk-todolist-done`元素，修改main.css中的此处的width，并不能让时间不换行，在浏览器中检视，发现是它被`element.style{ width:2.6em;}`所覆盖，目前我无法定位到是哪个js覆盖了main.css的设置

**Comment by linonetwo** [comment]
这里的模板里的样式修改主要来自 https://github.com/tiddly-gittly/itonnote-theme

你可以确认一下在这里面的demo页面上是否也有这个问题，如果有的话，可以修改这个仓库里的样式，以便其他用户也能享受无冲突的样式表。

**Comment by YrracOwl** [comment]
> 

确认了，存在这个问题，但是怎么改我还没有头绪，我晚上看看

**Comment by YrracOwl** [comment]
在demo页面上又重新查看了一下，不知道是不是跟windows版本相关。在demo页面上win7上显示会错位而win10没有。

**Comment by linonetwo** [comment]
可能是浏览器版本的问题吧

**Comment by YrracOwl** [comment]
今天把相关插件好像有更新，更新完毕问题结局
