### ISSUE TITLE
help: 两台电脑同步，加密条目在其中一台无法查看

### ISSUE THREAD

**Issue by YrracOwl** [tiddly-gittly/TidGi-Desktop#314]
### Description 描述

两台PC均与仓库同步，显示无最新更改。但是在其中一台电脑上，标签<APrivarteContent>的条目无法查看，另一台是正常可查看的。

**Comment by linonetwo** [comment]
我没用过加密条目，那个不是输入密码才能解开的吗？还有如果都是同样的内容的话，为啥展示会有不同呢？你用github desktop看看同步过来之后具体的内容是不是一样的。

**Comment by linonetwo** [comment]
那就是没链接子wiki成功吧

**Comment by YrracOwl** [comment]
那这个应该怎么弄呢，有点头疼

**Comment by linonetwo** [comment]
就是创建 子wiki，这一步你有操作成功吗

**Comment by linonetwo** [comment]
检查一下 tiddlers 文件夹里的软连接有没有生成成功

**Comment by YrracOwl** [comment]
搞定了，在tiddler下生成了subwiki这个文件夹，那我要在多台设备上同步的话，就只有手动copy subwiki这个文件夹了吧？

**Comment by linonetwo** [comment]
![](https://user-images.githubusercontent.com/3746270/206972308-9e9a95b2-0419-40e0-8400-7c670eda9b72.png)

你是不是没用这个功能

**Comment by YrracOwl** [comment]
。。。我没有这个"子知识库将连接到/Path"这句话，我用的win

**Comment by linonetwo** [comment]
那说明你在添加的是主知识库呀，有个开关，你改一下，让它是添加子知识库就行了。

**Comment by YrracOwl** [comment]
我找到子知识库了，但是这个文件结构我没太懂。我新建子知识库，子知识库命名为subTiddlyWiki，那么它就是会在主知识库下的tiddler/subwiki里面创建一个子链接，然后我的APrivateContent标签的条目是放在和subTiddlyWiki同级的private-wiki里的，似乎没有成功软链接

![image](https://user-images.githubusercontent.com/37571668/207204858-ec12be15-677e-440a-a6e4-9965b9a3cf4e.png)

**Comment by YrracOwl** [comment]
确实如此，我改一下FileSystemPaths.tid的规则应该就可以正确地把subwiki的内容放到子知识库里面了，但是好像按照下面这个规则：

```js
[!is[system]kin::to[APrivateContent]addprefix[subwiki/private-wiki/]]
[!is[system]kin::to[Photos]addprefix[subwiki/private-wiki-photos/]]
```

创建的文件夹跟子知识库的路径似乎又耦合？

还是说我必须要首先新建子知识库，然后才能用APrivateContent这个标签

**Comment by YrracOwl** [comment]
啊我理解了，就是说，我创建的子知识库，要以`subwiki/private-wiki/`里面的`private-wiki`为命名。

TidGi新建子知识库的那个指引感觉有点误导，如下图。

![image](https://user-images.githubusercontent.com/37571668/207220335-eba0220d-7e82-4d6e-85ca-1485f4c9b025.png)

实际在这个`tiddler/private-wiki-photos`中还有一层`tiddler/subwiki/private-wiki-photos`，而且有另一个问题：子文件夹打不开，一点打开就报内部js错误了

**Comment by linonetwo** [comment]
哦对，这个显示问题之后改改

报错我没遇到过

**Comment by YrracOwl** [comment]
![image](https://user-images.githubusercontent.com/37571668/207478619-43ac3ed2-b800-43d1-b1cc-25499d43e0d5.png)

报错是这个，说没有token，但是我这俩私人wiki都已经上传成功了

**Comment by linonetwo** [comment]
你可能不是 js 程序员，这个是说 js 解析器说有未知 token 啦，最好用右键开发者工具的 console 看一下具体的报错位置，好排查一下是什么的问题。

有可能是太极里面我啥写错了

**Comment by YrracOwl** [comment]
![image](https://user-images.githubusercontent.com/37571668/207489504-d2347c1d-e4cb-42eb-b740-ebe4a307dbe0.png)

在这里，这个我就排查不了了，靠你了

**Comment by linonetwo** [comment]
这样看不出来，你得点进  VM533:11 那边，看到具体是哪行代码才行。

不过太极一般是不会出这种错的，我也没遇到过。

**Comment by YrracOwl** [comment]
```js
    while (currentHandlerWidget && !handled) {
      const bubbled = currentHandlerWidget.dispatchEvent({ type: "tm-navigate", navigateTo: "APrivateContent
", param: "APrivateContent
" });
      handled = !bubbled;
      currentHandlerWidget = currentHandlerWidget.children?.[0]
    }
```

这个，第二行，奇怪

**Comment by linonetwo** [comment]
我知道了，是因为

```
"APrivateContent
"
```

这里换行了，这个js是字符串拼接生成的，我有空修一下

**Comment by YrracOwl** [comment]
OKK
