### ISSUE TITLE
bug: Uncaught TypeError: Cannot read properties of undefined (reading 'attach')

### ISSUE THREAD

**Issue by YrracOwl** [tiddly-gittly/TidGi-Desktop#316]
### Environment 环境信息

Version v0.7.12-prerelease2.

Electron Version: 21.3.0
Node Version: 16.16.0
Chromium Version: 106.0.5249.181

### Description 描述

![image](https://user-images.githubusercontent.com/37571668/208032021-9b6ef39b-437c-4936-bd96-7bf297a5552e.png)

控制台抓的数据如下：

![image](https://user-images.githubusercontent.com/37571668/208032103-26b7c4fe-eea8-46f4-b2c9-8a4236b97c68.png)

boot.js:214显示如下：

![image](https://user-images.githubusercontent.com/37571668/208032209-dcd4b4dc-2718-4053-b60b-c12b4b0ecccd.png)

### Steps to Reproduce 复现方式

可能是添加了图片的原因？我在tiddler里插入了图片，其他的就是正常的tiddlywiki格式的文本。

**Comment by linonetwo** [comment]
是不是所见即所得的情况下插入的图片，那个还没适配过

**Comment by YrracOwl** [comment]
那个状态我点过一次，然后整个编辑就会把我的`>>> <<<`引用的内容的换行取消，而且图片也显示不出来，后来就出这个错了，那应该就是这个的问题了

**Comment by linonetwo** [comment]
是的，你可以把有问题的引用内容提交到 [https://github.com/tiddly-gittly/slate-write](https://github.com/tiddly-gittly/slate-write) 的 issue ，之后我加入测试

**Comment by YrracOwl** [comment]
okk，提交了
