### ISSUE TITLE
bug: 通过导入WIki.html功能导入的wiki 似乎无法删除和更新插件

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#324]
### Environment 环境信息

TidGi (win32)
Version v0.7.13.

Electron Version: 22.0.0
Node Version: 16.17.1
Chromium Version: 108.0.5359.62

### Steps to Reproduce 复现方式

1. 导入单文件wiki
2. 删除一个插件（导入之前的插件），重启服务，插件重新出现。观察到删除插件并没有写入到文件系统中。（通过查看GitHub desktop的changes列表）
3. 更新插件也不行（导入之前的插件）。查看GitHub desktop的changes发现没有被写入文件系统。奇怪的是，安装插件的时候同时更新插件，插件虽然没有被写进文件系统，但还是更新了版本号。（不知道是不是偶然）

**Comment by Zacharia2** [comment]
拖放导入条目没有问题

**Comment by linonetwo** [comment]
但是往里面写笔记是能正常保存的吧，插件应该没什么不同才对

**Comment by Zacharia2** [comment]
对写笔记没有问题

**Comment by Zacharia2** [comment]
我会测试一下各种情况的，然后放在这里。

**Comment by Zacharia2** [comment]
1. 在太记中导入后的wiki.html，使用**创建一个新的条目**按钮，创建各种类型的条目，以及添加字段均无问题。

**Comment by Zacharia2** [comment]
1. 从外部拖入一个插件，可以在github中看到修改，重启服务也并无问题，插件安装成功。
2. 删除这个插件，发现GitHub中该插件json文件消失，重启服务后，插件删除成功。
3. 将插件导出为json文件，然后拖放进wiki，与上述现象相同，均可以安装成功与删除成功。

**Comment by Zacharia2** [comment]
在控制面板中，我选中信息选项卡，侧边栏调整为开启选项卡，重启服务后，恢复为导入之前的单文件wiki设置。即外观选项卡与favorite选项卡。在GitHub中也未有修改。

**Comment by Zacharia2** [comment]
接下来我会测试不使用太记的导入单文件wiki的功能，而通过nodejs版tiddlywiki的解压功能解压后导入太记，看看能不能删除和更新插件。

**Comment by Zacharia2** [comment]
使用nodejs版tiddlywiki解压后的wiki导入太记，可能由于懒加载，“Save snapshot for offline use” 功能在保存为单文件wiki时，大部分图片显示为空白。但是通过

```
window.service.wiki.packetHTMLFromWikiFolder("D:\\Dropbox\\21-Sandox\\40-Wiki\\墨屉TiddlyWiki简易指南", "C:\\Users\\Mxun\\Desktop\\11.html")
```

导出的单文件wiki却没有任何问题。

**Comment by Zacharia2** [comment]
使用nodejs版tiddlywiki解压wiki，然后使用TidGi导入wiki，删除其中一个插件，观察GitHub中的文件变化，发现没有修改。重启服务后插件并未被删除。

**Comment by Zacharia2** [comment]
综上所述，猜测使用TidGi的导入wiki.html功能与使用nodejs版tiddlywiki解压wiki，然后使用TidGi导入wiki几乎功能完全相同。

使用TidGi的导入wiki.html功能的wiki，所有功能均可使用，只是删除和更新插件不可用，似乎像是冻结了一般。同时修改默认侧边栏页签不起作用，修改其它配置没有问题，但也没有全部测试，仅测试了驼峰wiki链接，外观选项卡的视图模式，工具栏。

**Comment by Zacharia2** [comment]
以上仅测试了我能够想到的所有情况，具体原因未知

**Comment by Zacharia2** [comment]
还发现一个问题，无论使用那种方式（TidGi的导入单文件wiki还是使用nodejs导入单文件wiki），只要在TidGi中执行此命令

window.service.wiki.packetHTMLFromWikiFolder("C:\Users\Mxun\Desktop\mywiki", "C:\\Users\\Mxun\\Desktop\\mywiki.html") 

就会产生这个现象。

![image](https://user-images.githubusercontent.com/32425955/209255654-857f7495-2cea-4d76-9ea8-341ddf35d11c.png)


不过使用nodejs执行 tiddlywiki  ./mywiki1  --rendertiddler  '$:/core/save/all'  mywiki.html  text/plain 对使用TidGi导入单文件wiki功能解压的wiki进行打包后，发现是正常的。

出现错误的现象的一种可能性（已验证）是，打包的文件夹填写错误或者不存在（./mywiki1这个参数错写或者漏写或者不存在）

以确认这个命令的文件夹位置书写无误。
window.service.wiki.packetHTMLFromWikiFolder("C:\Users\Mxun\Desktop\mywiki1", "C:\\Users\\Mxun\\Desktop\\mywiki1.html")

奇怪的是tiddlywiki简易教程之墨屉钓鱼版却可以使用window.service.wiki.packetHTMLFromWikiFolder这个命令，并且完美的打包好。

**Comment by Zacharia2** [comment]
window.service.wiki.packetHTMLFromWikiFolder的参数定义：https://github.com/tiddly-gittly/TidGi-Desktop/blob/a5a2bb6e0009d923284509b54aba7e69adc5ee0c/src/services/wiki/wikiWorker.ts#L187

**Comment by Zacharia2** [comment]
使用nodejs版tiddlywiki解压后的wiki导入太记，可能由于懒加载，“Save snapshot for offline use” 功能在保存为单文件wiki时，大部分图片显示为空白。但是通过

```
window.service.wiki.packetHTMLFromWikiFolder("D:\\Dropbox\\21-Sandox\\40-Wiki\\墨屉TiddlyWiki简易指南", "C:\\Users\\Mxun\\Desktop\\11.html")
```

导出的单文件wiki却没有任何问题。

**Comment by linonetwo** [comment]
> 可能由于懒加载，“Save snapshot for offline use” 功能在保存为单文件wiki时，大部分图片显示为空白

是的，因为有 lazy image，而那个导出没考虑这一点。

`window.service.wiki.packetHTMLFromWikiFolder` 是在后端执行的，自然能获取到完整的 wiki内容。之后或许可以改一下 Save snapshot for offline use 的实现，让它在太记里就直接掉这个

**Comment by linonetwo** [comment]
> 属于单文件wiki时期（未解压也为导入TidGi时期）就已经安装的插件，似乎删除不了，也无法更新

这个我有空看看吧，可能它导入后产生的插件 tid 文件（或是 json 文件）有什么格式上的特殊之处，我已经看到各插件作者生成出好几种插件的不同 json 格式了，其中有一些应该是不对的。

**Comment by Zacharia2** [comment]
> `window.service.wiki.packetHTMLFromWikiFolder` 是在后端执行的，自然能获取到完整的 wiki内容。之后或许可以改一下 Save snapshot for offline use 的实现，让它在太记里就直接掉这个

要注意的是不同平台的目录分隔符，Windows是双斜杠。

**Comment by Zacharia2** [comment]
忘记一种在nodejs下删除和更新的情况，今天测试看看。

**Comment by Zacharia2** [comment]
把TidGi解压的wiki使用nodejs打开，升级与卸载插件都可以正常进行

**Comment by Zacharia2** [comment]
总的来说，我感觉不太重要，只是不能在太记中升级与卸载插件而已，用其它方式解决也可以。

**Comment by linonetwo** [comment]
这个过段时间再研究，最近我要先解决nodejs wiki的性能问题，不然我记日记老卡

**Comment by Zacharia2** [comment]
嗯呢，是的，确实有点卡

**Comment by Zacharia2** [comment]
也许是因为太记中的插件是存放在tiddler文件夹以JSON文件存在的，而解压后的wiki的插件是用plugin文件夹以条目形式存在的。

**Comment by linonetwo** [comment]
这样子呀，那可能得在解压之后自动把这些文件都统一放到tiddlers文件夹里，因为从CPL安装的插件都会自动放到那边。而现在我们把cpl当成默认的安装方式了。

**Comment by dongrentianyu** [comment]
我今天也发现了这个问题。解压出来的插件是有一个独立的插件文件夹，然后每一个插件也会有一个独立文件夹，就无法通过插件库来安装和更新插件。

太记是把这些都和普通条目放在一起的。

所以解决办法也就是手动把之前的插件文件夹删除，然后再找一个太记模板，插件与普通条目放在一起的，找出所以系统条目，复制过来。就可以了。但一些配置需要自己再手动调整一下。

这是手动处理的方式。真正解决只有等后面再修了。

**Comment by dongrentianyu** [comment]
这个操作还是很复杂的样子。其实要是没有做不太个人自定义设置的话，直接导出所有条目，然后导入到太记的新wiki里去，再配置一下插件就好了。如果有很多个这样的话，就可以搞一个自己的模板插件，然后想用的时候就直接复制模板插件了。

**Comment by Zacharia2** [comment]
> 这个操作还是很复杂的样子。其实要是没有做不太个人自定义设置的话，直接导出所有条目，然后导入到太记的新wiki里去，再配置一下插件就好了。如果有很多个这样的话，就可以搞一个自己的模板插件，然后想用的时候就直接复制模板插件了。

这是对太记开发来说的。不的对用户来说的。

**Comment by dongrentianyu** [comment]
这样能实现吗？因为解析过程中不是原生太微里设置的吗？好像太记无法修改吧。

**Comment by linonetwo** [comment]
今天试了一下在 extractWikiHTML 的最下面加上

```ts
  try {
    const pluginFolderPath = path.join(saveWikiFolderPath, 'plugins');
    // DEBUG: console pluginInfo
    console.log(`packetHTMLFromWikiFolder pluginFolderPath 0`, pluginFolderPath);
    // DEBUG: console pluginInfo
    const pluginInfo = wikiInstance.loadPluginFolder(pluginFolderPath);
    console.log(`packetHTMLFromWikiFolder pluginInfo 0`, pluginInfo);
    // DEBUG: console pluginInfo
    console.log(`packetHTMLFromWikiFolder pluginInfo 1`, JSON.stringify(pluginInfo, null, '  '));
  } catch (error) {
    // DEBUG: console error
    console.log(`packetHTMLFromWikiFolder error 2`, error);
  }

  try {
    const pluginFolderPath1 = path.join(saveWikiFolderPath, 'plugins', 'commander');
    // DEBUG: console pluginInfo
    console.log(`packetHTMLFromWikiFolder pluginFolderPath1 2`, pluginFolderPath1);
    const pluginInfo1 = wikiInstance.loadPluginFolder(pluginFolderPath1);
    // DEBUG: console pluginInfo
    console.log(`packetHTMLFromWikiFolder pluginInfo 2`, pluginInfo1);
    // DEBUG: console pluginInfo
    console.log(`packetHTMLFromWikiFolder pluginInfo 3`, JSON.stringify(pluginInfo1, null, '  '));
  } catch (error) {
    // DEBUG: console error
    console.log(`packetHTMLFromWikiFolder error 3`, error);
  }
```

不知道为什么会卡在 wikiInstance.loadPluginFolder(pluginFolderPath) 这一步，就不往下走，也不报错，很奇怪

**Comment by linonetwo** [comment]
我看估计就是用 loadPluginFolder ， @Zacharia2 你感兴趣可以试试

**Comment by linonetwo** [comment]
<img width="254" alt="截屏2023-05-21 23 21 39" src="https://github.com/tiddly-gittly/TidGi-Desktop/assets/3746270/057978ee-012f-43d1-8f2d-62e99fd1c829">

不知为啥有的插件比如 focused-tiddler 里面是空的

**Comment by linonetwo** [comment]
其实也可以看看能不能从 wikiInstance 里直接取到插件的 json，然后仿照 https://github.com/tiddly-gittly/tw5-plugin-packer/blob/435e61877ed262eb42832f7232dd86919ebc6377/packup.js#L57 来用

**Comment by Zacharia2** [comment]
好滴

**Comment by linonetwo** [comment]
看 https://github.com/Jermolene/TiddlyWiki5/issues/7472#issuecomment-1556789379 ，Jeremy 说可以提 PR 在核心上加一个参数，让它不要把插件放进 plugins 文件夹。 @Zacharia2 你有空可以研究这个，这应该是最直接最简单的方案

**Comment by Zacharia2** [comment]
好的，感觉挺难的，我有空可以试试它。

**Comment by Zacharia2** [comment]
备忘录：

--savewikifolder ./mywikifile.html explodeplugins=no

https://github.com/Jermolene/TiddlyWiki5/blob/3f763775d68fbb1f5c4e403cf384affe71809ff4/core/modules/commands/savewikifolder.js#L29

**Comment by dongrentianyu** [comment]
我觉得可以写个bat文件，先解压，后移动插件文件夹，这样应该会更简单一点。

**Comment by Zacharia2** [comment]
融合进GUI是最简单的。

**Comment by dongrentianyu** [comment]
能融合进去那肯定是最好的，但我感觉这难度不小。如果可以的话，还可以多加一个，就是导出多个条目为tid格式。但感觉上这就很有难度。

**Comment by Zacharia2** [comment]
fix #7472 add option explodeplugins  已经完成所有工作（完善翻译文档，实现向后兼容并实现下列参数输入形式等等），下列形式测试没有问题了。

```
--savewikifolder <wikifolderpath> explodePlugins=no
--savewikifolder <wikifolderpath> [all[tiddlers]] explodePlugins=no
--savewikifolder <wikifolderpath> filter=[all[tiddlers]] explodePlugins=no

--savewikifolder <wikifolderpath> [ [<name>=<value>] ]* 
--savewikifolder <wikifolderpath>
--savewikifolder <wikifolderpath> [<filter>]
--savewikifolder <wikifolderpath> [<filter>] [ [<name>=<value>] ]*
```

**Comment by dongrentianyu** [comment]
太厉害了。

**Comment by Zacharia2** [comment]
终于解决了，杰里米合并了我的pr。太记以后就可以无缝衔接单文件wiki啦。
