### ISSUE TITLE
bug: -108 ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by cnsdly** [tiddly-gittly/TidGi-Desktop#332]
## Environment

TidGi 0.7.14
Electron 22.0.0
win32 10.0.18363
Locale: ja

## Additional Context

```typescript
Error: -108 ERR_ADDRESS_INVALID
```
[TidGi-2023-01-10.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/10380104/TidGi-2023-01-10.log)

---

**Comment by linonetwo** [comment]
http://0.0.0.0:5212/#%E6%B5%8B%E8%AF%95:%E6%B5%8B%E8%AF%95 ERR\_ADDRESS\_INVALID (-108) loading 'http://0.0.0.0:5212/#%E6%B5%8B%E8%AF%95:%E6%B5%8B%E8%AF%95' Error: ERR\_ADDRESS\_INVALID (-108)

**Comment by linonetwo** [comment]
看起来不像有问题的网址，你注意防火墙要允许访问

**Comment by linonetwo** [comment]
你是日本人吗？感兴趣的话，你可以提交一下日语的翻译啊。
