### ISSUE TITLE
feature: 侧边栏可以选择移除图标吗？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#333]
### Description 描述

因为笔记本电脑屏幕比较小，而平时开的wiki又比较多，导致我现在切换wiki时，通过侧边栏直接切换的方式感觉不太流畅。

<img width="64" alt="image" src="https://user-images.githubusercontent.com/109711900/211582123-0d4e8b92-acb0-4a2f-8387-1891031d01ce.png">

而我平时也不会去设置图标，所以我就想着移除或者可选的，展示图标还是精简模式下，只显示文字标题。

这样我在多个wiki来回切换会很方便。

我知道可以右键选择，但右键选择的话反而更慢，右键选择只适合一次性跳转过去，而有时会需要频繁来回切换wiki，或查看问题，或编辑更新。

**Comment by linonetwo** [comment]
哦，理解了，你的工作区比较多，然后想让左边多展示几个。这的确是可以。

**Comment by dongrentianyu** [comment]
太好了，坐等更新后的效果。期待中。

**Comment by linonetwo** [comment]
你直接下预发布版的试试 https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.7.15-prerelease 在设置里改一下
