### ISSUE TITLE
bug: Cannot read properties of null (reading 'reload') 无法

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#336]
## Environment

TidGi 0.7.14
Electron 22.0.0
win32 10.0.22000
Locale: zh-CN

## Description:

无法加载。昨天还可以加载编辑的。

## Additional Context

```typescript
TypeError: Cannot read properties of null (reading 'reload')
    at C:\Users\34656\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1702546
    at C:\Users\34656\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1701291
    at Array.forEach (<anonymous>)
    at C:\Users\34656\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1701240
    at Array.forEach (<anonymous>)
    at Qo.forEachView (C:\Users\34656\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1701178)
    at Qo.reloadViewsWebContents (C:\Users\34656\AppData\Local\TidGi\app-0.7.14\resources\app.asar\.webpack\main\index.js:2:1702479)
```

---

[D__太记_常用wiki专属备份_serious_opennote_WENAI.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/10407679/D__._.wiki._serious_opennote_WENAI.log)

**Comment by dongrentianyu** [comment]
同时报告另一个问题，就是我有一个taiji的本地仓库，在本地显示是好的，在github仓库里也有条目存在。但在网址上显示不出来。

<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/212225528-175d1521-9b8a-49ea-8a5d-dbbf2116994a.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/212225604-ceefed75-1673-44bd-adaa-e285c55ef5de.png">



我怀疑是打包文件落后导致的。因为我在本地的版本是5.2.6-prerelease-2022-12-20，而显示网址的版本是5.2.3-prerelease-2022-04-09。所以可能是版本不一致导致的问题。

太记是最新版本。



</body>
</html>

**Comment by dongrentianyu** [comment]
[D__太记_常用wiki专属备份_test_taiji.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/10407729/D__._.wiki._test_taiji.log)

同样上传一份taiji仓库的log文件。不知道有没有作用。

**Comment by linonetwo** [comment]
你记得更新一下 package.json 里的版本，保持和 

https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template/blob/8a465b27541f310ae59d84774df7cdaa47c5eff1/package.json#L6

一致

**Comment by linonetwo** [comment]
应该是部署没成功，actions 那边没成功部署

**Comment by dongrentianyu** [comment]
可能当时操作出现了问题，后面知道怎样部署了，就解决了。但另一个问题是，我发现一些插件无法加载到网站上。比如codemirror插件。我在本地上编辑是打开了行号的。但在网站上编辑发现没有行号。查找后发现codemirror插件的条目都不存在。但在github的仓库上是存在的。

这个问题不知道是为什么。我清空了浏览器的缓存也没有效果。换了谷歌浏览器也没有效果。

**Comment by linonetwo** [comment]
你发个你的 action 的链接，可能里面有报错

**Comment by linonetwo** [comment]
[https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template/blob/8a465b27541f310ae59d84774df7cdaa47c5eff1/tiddlywiki.info#L36](https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template/blob/8a465b27541f310ae59d84774df7cdaa47c5eff1/tiddlywiki.info#L36)

你看这一行，我在部署博客时会去掉很多插件，你看是不是这个的问题，去掉了 codemirror

**Comment by linonetwo** [comment]
这些太微的配置、action 的配置，有机会我还是做成可视化配置来的好，但我一直没空加
