### ISSUE TITLE
bug: Fishing Analysis and Folder Menu don't respect language settings

### ISSUE THREAD

**Issue by shibacomputer** [tiddly-gittly/TidGi-Desktop#337]
### Environment 环境信息

Version v0.7.14.

Electron Version: 22.0.0
Node Version: 16.17.1
Chromium Version: 108.0.5359.62

### Description 描述

Thank you for this great implementation of TiddlyWiki!
On Fedora Linux, the localisation settings of Fishing Analysis and FolderMenu do not respect the rest of the application. Here are some screenshots:
![image](https://user-images.githubusercontent.com/737950/212350019-006ac02b-5440-4526-824c-816eac0eb3e9.png)

![image](https://user-images.githubusercontent.com/737950/212354686-dc348462-7302-4c55-8070-188e230c0bcb.png)

This is also true for the settings of both plugins:
![image](https://user-images.githubusercontent.com/737950/212354880-75855939-6db0-4686-9446-373055968136.png)

I am not sure whether this is the same issue, but switching to Chinese also fails to update plugin language settings:
![image](https://user-images.githubusercontent.com/737950/212355287-34f0175a-6602-4f61-b39e-110959368550.png)

### Steps to Reproduce 复现方式

1. Install latest release on Fedora 37
2. Switch language to English
3. Inspect FishingAnalysis or FolderMenu

**Comment by linonetwo** [comment]
For fishing plugin, you need to install english language pack, in fishing plugin library or CPL.

For Folder Menu, I didn't do i18n, because I don't know how https://talk.tiddlywiki.org/t/how-to-translate-3rd-party-plugin/5435

**Comment by linonetwo** [comment]
Are you using this?
