### ISSUE TITLE
bug: not support right to left languages

### ISSUE THREAD

**Issue by barooni** [tiddly-gittly/TidGi-Desktop#339]
### Environment 环境信息

Version v0.7.14.

Electron Version: 22.0.0
Node Version: 16.17.1
Chromium Version: 108.0.5359.62

### Description 描述

I test in both Persian and Arabic, weirdly, when I type (language in the system set to RTL langauges) it would still type in English.

Sometimes, it also shows a notification like "Persian is not supported in the Linux app yet" or something like that.

I expect to type in the language which is selected in the setting.

### Steps to Reproduce 复现方式

Just change your language to Persian or Arabic in Linux environment and try typing ... 

### Additional Context 额外上下文

I use ChromeOS not Linux, but since it virtualizes the Linux application it probably has the same effect.

**Comment by linonetwo** [comment]
Sorry for late reply, it was Chinese new year these days!

Do you mean can't use RTL input method in Tiddlywiki edit mode inside TidGi?

Can you try open the wiki in the browser, and try it again? You can right click workspace icon -> open in browser

**Comment by barooni** [comment]
> Do you mean can't use RTL input method in Tiddlywiki edit mode inside TidGi?

yes, at least for Persian and Arabic not working in Linux ...

> Can you try open the wiki in the browser, and try it again? You can right click workspace icon -> open in browser

I am able to write Persian and Arabic there, it seems the problem is related to Webcatalog. by the way, why is the IP address wired? I expect It to run on localhost but run from other IPs in HTTP, This raises my concerns about privacy.

**Comment by linonetwo** [comment]
Yes, there is supposed to be an option to disable listen on 0.0.0.0 , but this is low priority , waiting for other to PR this.

And I don't have a linux machine for this, you have to make it clear what happened, on browser side, or just in electron (yes you can test this with Webcatalog [https://webcatalog.io/?utm_source=tidgi_app](https://webcatalog.io/?utm_source=tidgi_app) )

**Comment by linonetwo** [comment]
If this also happened on browser side, maybe tw core have this problem too, or codemirror plugin have this problem too.

**Comment by linonetwo** [comment]
in latest prerelease, you can enable Token Auth to improve privacy!

**Comment by linonetwo** [comment]
> change your language to Persian or Arabic in Linux environment and try typing

Don't have method to test this, can you PR to fix this?
