### ISSUE TITLE
bug: Uncaught TypeError: Cannot read properties of undefined (reading 'syncadaptor')

### ISSUE THREAD

**Issue by inkydragon** [tiddly-gittly/TidGi-Desktop#346]
### Environment 环境信息

[Demo Online Web Blog Page](https://tiddly-gittly.github.io/Tiddlywiki-NodeJS-Github-Template/)

### Description 描述

Works fine, no errors reported.

### Steps to Reproduce 复现方式

Open the link.

![image](https://user-images.githubusercontent.com/5158738/219992578-de0e5c98-b468-4885-990a-6ca0b0311def.png)

**Comment by linonetwo** [comment]
![](https://user-images.githubusercontent.com/3746270/220130131-93b88606-a2b2-4280-abd4-a77455104aab.png)

Welcome, thanks, I will figure this out.

**Comment by linonetwo** [comment]
fixed

**Comment by linonetwo** [comment]
need force refresh
