### ISSUE TITLE
官网

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#348]
### Description 描述

/// 给用户答疑中

所以我现在对于新用户都直接推荐用太极，不用太记得，我都不咋理了。太极会直接带有美化和所念吉所得，用户就少了很多乱七八糟的问题其实很多人是不会去看插件的，第一眼看到啥样，就以为太妃是啥样所以推荐的时候尽量就推已经预装好东西了版本

pimgeek：我建议创建一个简版官网，像 Obsidian 或 Logseq 那样，把 TiGit 做成巨大的下载按钮，然后其它细节全部藏进 Learn More 链接里面

我：然后可以说are you a geek, If so, you can try your own PIM app from the ground up.

https://wiki.onetwo.ren/%E5%A4%AA%E5%BE%AE%E6%98%AF%E5%BC%80%E5%8F%91%E6%A1%86%E6%9E%B6%EF%BC%8C%E4%B8%8D%E6%98%AF%E7%AC%94%E8%AE%B0%E8%BD%AF%E4%BB%B6

### Additional Context 额外上下文

https://talk.tiddlywiki.org/t/landing-pages-can-tiddlywiki-learn-from-them/4942/79

**Comment by fcjz** [comment]
这个issue错别字好多啊，建议修改。

**Comment by linonetwo** [comment]
我基本都是语音输入打的

**Comment by linonetwo** [comment]
搞出来了！就在 tidgi.fun
