### ISSUE TITLE
bug: 切换成白板后报错

### ISSUE THREAD

**Issue by ming188199** [tiddly-gittly/TidGi-Desktop#355]
### Environment 环境信息

TidGi (darwin)
Version v0.7.14.

Electron Version: 22.0.0
Node Version: 16.17.1
Chromium Version: 108.0.5359.62

### Description 描述

内部的 JavaScript 错误
喔，真是令人尴尬。建议刷新您的浏览器，重新启动 TiddlyWiki
Uncaught TypeError: Cannot read properties of undefined (reading 'children')

### Steps to Reproduce 复现方式

1. 切换到白板模式
2. 然后点了一些操作不久就报错了。

**Comment by ming188199** [comment]
将文件（$__StoryList.tid）更改回去就能正常显示了。

@ -1,2 +1,3 @@
list: Index GettingStarted
title: $:/StoryList
title: $:/StoryList
type: text/vnd.tiddlywiki

**Comment by linonetwo** [comment]
可惜了，我想看的是报错具体在哪一行，就是红字得点进去复制

只这样看不出有什么问题

**Comment by linonetwo** [comment]
你要是还能复现就再贴一下具体哪个js文件的哪个行数

**Comment by linonetwo** [comment]
https://tw-cn.netlify.app/#%E5%85%B6%E5%AE%83%E7%BA%A2%E6%A1%86%E6%8A%A5%E9%94%99%E6%8E%92%E6%9F%A5
