### ISSUE TITLE
bug:  在 Windows on Arm 上不可用

### ISSUE THREAD

**Issue by huangyinhaow** [tiddly-gittly/TidGi-Desktop#357]
### Environment 环境信息

处理器	Snapdragon (TM) 8cx Gen 2 @ 3.0 GHz   3.00 GHz
机带 RAM	8.00 GB (7.65 GB 可用)
系统类型	64 位操作系统, 基于 ARM 的处理器
笔和触控	为 10 触摸点提供笔和触控支持
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2023/‎1/‎15
操作系统版本	22621.1344
体验	Windows Feature Experience Pack 1000.22639.1000.0

### Description 描述

arm64版本安装完成后，无法启动程序。

我尝试过最新的3个版本。

我无法看到任何图形界面，在终端中启动也只能看到 Starting 而无法看到任何错误报告。

### Steps to Reproduce 复现方式

正常安装，然后打开程序。

### Additional Context 额外上下文

本机装有node环境，node.js-18.11.0 arm版本 位于 path 中。

**Comment by linonetwo** [comment]
没有 arm 机器可以测试啊，能安装成功的话，看看 log 吧，应该在 application support / Tidgi /Logs 里

**Comment by huangyinhaow** [comment]
> 没有 arm 机器可以测试啊，能安装成功的话，看看 log 吧，应该在 application support / Tidgi /Logs 里

Windows 没有 application support 文件夹呀

**Comment by linonetwo** [comment]
【Windows 中不同位置的 AppData 文件夹都是用来干什么的？| ThioJoe [3XjSTG-oIMw]-哔哩哔哩】 https://b23.tv/ct6wxcz


应该是 appdata

**Comment by huangyinhaow** [comment]
[TidGi-Exception-2023-03-10.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/10952782/TidGi-Exception-2023-03-10.log)

**Comment by linonetwo** [comment]
`2adfab8e-cabb-4083-b60e-03eaf8982c6c.tmp.node is not a valid Win32 application` 你的是 32 位还是 64 位的

**Comment by huangyinhaow** [comment]
我不知道你指的是什么，我的系统详细信息已经放在上面了。文章中我指出，是arm64版本的TidGi-Desktop不可用。

发件人: lin ***@***.***>
发送时间: 2023年3月13日 10:22
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [tiddly-gittly/TidGi-Desktop] bug: 在 Windows on Arm 上不可用 (Issue #357)


2adfab8e-cabb-4083-b60e-03eaf8982c6c.tmp.node is not a valid Win32 application 你的是 32 位还是 64 位的

―

**Comment by huangyinhaow** [comment]
> 【Windows 中不同位置的 AppData 文件夹都是用来干什么的？| ThioJoe [3XjSTG-oIMw]-哔哩哔哩】 https://b23.tv/ct6wxcz
> 
> 应该是 appdata

谢谢指点！我会在我的空余时间尝试自己编译，再次感谢你如此及时地做出回复。

**Comment by linonetwo** [comment]
试试最新版还有问题吗 https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.8.0-prerelease5

**Comment by huangyinhaow** [comment]
> 试试最新版还有问题吗 https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.8.0-prerelease5

可以了！
