### ISSUE TITLE
bug: -300 ERR_INVALID_URL

### ISSUE THREAD

**Issue by Mzpd** [tiddly-gittly/TidGi-Desktop#362]
## Environment

TidGi 0.7.15-prerelease
Electron 22.0.0
win32 10.0.19045
Locale: zh-CN

## Additional Context

```typescript
Error: -300 ERR_INVALID_URL
```

---

**Comment by linonetwo** [comment]
![图片](https://user-images.githubusercontent.com/3746270/229270668-4eade128-7edd-4cd0-8cd7-70788bc5eebf.png)
![截屏2023-04-01 14 53 49](https://user-images.githubusercontent.com/3746270/229270683-9a128994-af5e-482b-8d89-a578c553d1a8.png)
