### ISSUE TITLE
bug: 同步失败报错退出后 太记程序无法启动

### ISSUE THREAD

**Issue by maozhijie** [tiddly-gittly/TidGi-Desktop#363]
### Environment 环境信息

win11 x64

### Description 描述

在出现网络问题同步失败后后,持续弹出多个需要确认的报错窗体,然后程序关闭

### Steps to Reproduce 复现方式

不确定

### Additional Context 额外上下文

[TidGi-2023-04-04.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/11145001/TidGi-2023-04-04.log)
[TidGi-Exception-2023-04-04.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/11145002/TidGi-Exception-2023-04-04.log)

**Comment by maozhijie** [comment]
重装无法解决问题,需要把C:\Users\NUC\AppData\Roaming下的相关文件删除,再次重装恢复正常

**Comment by maozhijie** [comment]
运行时系统网络代理状态不正常

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TidGi-Desktop/issues/354

看log和这个应该是同一个问题
