### ISSUE TITLE
bug: TidGi双击exe文件打不开

### ISSUE THREAD

**Issue by YrracOwl** [tiddly-gittly/TidGi-Desktop#366]
### Environment 环境信息

由于打不开TidGi，所以暂时无法给出一个环境信息
OS: win11 22H2

### Description 描述

双击exe之后，任务管理器显示3个TidGi的进程，经过大约3s以后全部被杀掉。

### Steps to Reproduce 复现方式

暂无

**Comment by linonetwo** [comment]
我也是 win11，我这没问题，你发 log 吧，在 C:\Users\linonetwo\AppData\Roaming\TidGi

**Comment by YrracOwl** [comment]
看了你的回复，我去找了下这个log，破案了。

> Setting file format bad

我把文件夹里的settings.json删了就好了，只不过保存的设置和wiki都不显示了，要重新添加，不知道为什么会突然坏掉
