### ISSUE TITLE
bug: deepin目前不支持zstd格式打包的deb安装包。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#369]
### Environment 环境信息

Deepin Linux 平台TidGi

### Description 描述

```sh
uses unknown compression for member 'control.tar.zst', giving up.
```

### Steps to Reproduce 复现方式

https://bbs.deepin.org/zh/post/235873

**Comment by Zacharia2** [comment]
手动解决方案：手拆zstd格式deb安装包，重新打包后安装

**Comment by Zacharia2** [comment]
备忘录：

dpkg -X ./xxx.deb extract

dpkg -e ./xxx.deb extract/DEBIAN

dpkg -b 文件夹 文件名.deb

sudo dpkg -i 文件名.deb


解压命令：tar -zxvf 压缩文件名.tar.gz

解压到指定目录：tar -zxvf 压缩文件名.tar.gz   -C   <目标目录>

压缩命令：tar -zcvf 压缩文件名.tar.gz <被压缩的文件夹>

**Comment by Zacharia2** [comment]
仅需要解压deb包中的这两个压缩包：data.tar.gz、ontrol.tar.gz。

新建一个文件夹tidgi-extract，control.tar.gz解压到tidgi-extract文件夹下的DEBIAN目录，data.tar.gz解压到tidgi-extract文件夹下。

然后在终端中执行 dpkg -b tidgi-extract TidGi.deb

**Comment by Zacharia2** [comment]
所以解决方法就是打包用的Ubuntu环境降低一点点就可以了，可以使用Ubuntu20.04

**Comment by Zacharia2** [comment]
> Ubuntu 通过博客终于决定将从 Ubuntu 21.10 开始使用 Zstd 压缩.deb 包。

**Comment by linonetwo** [comment]
所以其实是用户的 ubuntu 版本过低，所以无法解压这种包吗？现在 Ubuntu 大家还有用 20 的吗

**Comment by Zacharia2** [comment]
@linonetwo 大概是这个意思，其实只要低于Ubuntu 21.10 ，dpkg版本就会使用原有的压缩方式。

**Comment by linonetwo** [comment]
这个新版软件包有什么优势吗，没啥区别就先降级 Action 里的 ubuntu 吧

**Comment by Zacharia2** [comment]
> 这个新版软件包有什么优势吗，没啥区别就先降级 Action 里的 ubuntu 吧

就是速度相对快一点点。

**Comment by Zacharia2** [comment]
我用Ubuntu22.04测试过了，可以正常解压安装。
