### ISSUE TITLE
E-8 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug -324 ERR_EMPTY_RESPONSE http://0.0.0.0:5212

### ISSUE THREAD

**Issue by wxsblue** [tiddly-gittly/TidGi-Desktop#376]
## Environment

TidGi 0.7.15-prerelease
Electron 22.0.0
win32 10.0.19043
Locale: zh-CN

## Additional Context

```typescript
Error: -324 ERR_EMPTY_RESPONSE
```

---

**Comment by linonetwo** [comment]
一般右键刷新页面或重启服务即可，你看看哪个有效，反馈一下
