### ISSUE TITLE
bug: 【幽灵问题】编辑时，有时点击位置与光标位置对不上或者异常

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#382]
### Environment 环境信息

TidGi (win32)
Version v0.7.15-prerelease.

Electron Version: 22.0.0
Node Version: 16.17.1
Chromium Version: 108.0.5359.62

### Description 描述

在编辑时，我点击一行的右下角，光标却实际点击的左上角，或者干脆点击其它行。

### Steps to Reproduce 复现方式

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/637d45be-acf0-40f8-81a8-79dc807f051b)

编辑时有一定几率出现。

**Comment by linonetwo** [comment]
你看纯 html 版有没有问题，是不是主题的问题，一般不是 Electron 的问题

**Comment by linonetwo** [comment]
我发现 vanilla 主题就没事，要是有空的话，你可以二分删除 Itonnote 主题里的 css，看看是什么导致的。

我发现点开某个插件的 js 文件，基本可以稳定复现这个问题，就可以试了
<img width="898" alt="截屏2023-05-19 21 53 37" src="https://github.com/tiddly-gittly/TidGi-Desktop/assets/3746270/c0aaffaa-9c4d-4e8f-a7f8-074522c191f2">

**Comment by Zacharia2** [comment]
OK，我试试

**Comment by Zacharia2** [comment]
这似乎是一个玄学问题。。。我单独删掉linonetwo_itonnote插件问题还是有。但我删除所有codemirror问题就消失了。但是我之前的单文件版本就没有这个问题！我的单文件版本和太记的codemirror全部一样。

**Comment by Zacharia2** [comment]
我定位不到具体的位置。ε=(´ο｀*)))唉

**Comment by Zacharia2** [comment]
用太记打开的太微中文教程好像没有这个问题。

**Comment by dongrentianyu** [comment]
根据https://github.com/codemirror/codemirror5/issues/5724这个下面的回答，我猜测是itonnote主题插件自带了一个字体，导致打开js条目的时候dom需要重新加载一下还是计算一下。

我这测试了几次，就是只有刚开始一次会有这样的效果。后面就不会有这样的效果了。

**Comment by dongrentianyu** [comment]
ok，我刚测试了一下，基本上就是Fira Code字体问题。如果新建一个wiki，先去把这个字体删除。然后再打开js条目，就不会出现上面的问题了。

**Comment by dongrentianyu** [comment]
如果一直出现就可以删除这个字体。其他时候能正常使用，就没必要太在意了。

**Comment by dongrentianyu** [comment]
我猜测应该都会有问题，就是第一次的时候卡一下，后面其实挺正常的。我用起来也没问题。

**Comment by Zacharia2** [comment]
WhiteFall 8:41:40
哦，我明白了，编辑器字型不能有字体。

WhiteFall 8:43:23
问题解决，正是这个缘故。编辑器字型不能有字体。

**Comment by linonetwo** [comment]
按理来说是可以有字体的，可能就是 codemirror 需要额外适配吧，自带的普通编辑器应该没问题

**Comment by linonetwo** [comment]
是不是第一次打开编辑器才会这样，之后在wiki刷新前就不会多次出现了

**Comment by Zacharia2** [comment]
是的，第一次打开编辑器才会这样。但我之前遇到打开很长时间了也会这样。

**Comment by Zacharia2** [comment]
但是我的单文件版本也装了和太记模版一样的codemirror，但没遇到问题。

**Comment by Zacharia2** [comment]
不行，还是不对。不知道是什么问题。我不光把太记的那个字体删除了，还删除了主题和插件，并清空了编辑器字形字体。在这个过程中我重启了一次。然后测试，但还是不行。

**Comment by Zacharia2** [comment]
令我好奇的是为啥太微中文教程没有这个问题。

**Comment by Zacharia2** [comment]
有时候会影响，就编辑的时候选不对地方就很难受。

**Comment by Zacharia2** [comment]
启用codemirror活动行高亮即可等效解决此问题。
