### ISSUE TITLE
bug:executing boot module $:/plugins/felixhayashi/vis/vis.js

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#385]
## Environment

TidGi 0.8.0-prerelease1
Electron 24.3.1
win32 10.0.22621
Locale: zh-CN

## Additional Context

```typescript
Error: [1;31mError executing boot module $:/plugins/felixhayashi/vis/vis.js: "Global assignment is not allowed within modules on node."

undefined[0m

    at Object.next (C:\Users\34656\AppData\Local\tidgi\app-0.8.0-prerelease1\resources\app.asar\.webpack\main\index.js:2:1969444)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

---

**Comment by dongrentianyu** [comment]
[TidGi-2023-05-21.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/11524876/TidGi-2023-05-21.log)

先放log报错文件吧，回头我试着删除这个插件重新加载一下。太微中文社区因为没有这个插件所以加载起来没问题。

**Comment by flibbles** [comment]
Not sure. Sounds like TidGI is somehow making a more strict runtime environment.

I'd first recommend you update your TiddlyMap installation to the latest version (only available through git) and seeing if the issue is still there. The latest version no longer uses vis.js, but instead vis-network.js, which is a stripped down subset of the old library. It might not have the issue.

**Comment by dongrentianyu** [comment]
I updated the plugin to the latest version and it still gives me an error.

**Comment by flibbles** [comment]
Surely it's at least giving you a different stack trace. the flbbles/vis-network plugin has the core vis code in a different file. Can I see the new error message?

**Comment by linonetwo** [comment]
Why would a library plugin use the boot module?

And I cant get result of `Global assignment is not allowed within modules on node` on Google, this might be something new in Electron [24.3.1](https://releases.electronjs.org/release/v24.3.1)  chromium 112.0.5615.183  nodejs 18.14.0

**Comment by dongrentianyu** [comment]
Sorry, I originally recorded a gif file to demonstrate the process from installing the plugin to reporting an error, but the gif file was too big and couldn't be uploaded after compression. Overall there is no additional error reporting information though. All the error reporting messages are the same as above. You can try downloading the latest version of tidgit and install the tiddlymap plugin in Cpl. You can see the error reporting after restarting.

**Comment by flibbles** [comment]
If the stacktrace of the error message is exactly the same, then I believe that means you're not actually using vis-network, and you haven't properly upgraded to the latest TiddlyMap version. At the very least, it should be saying
```
Error executing boot module $:/plugins/flibbles/vis-network/vis.js ...
```

**Comment by dongrentianyu** [comment]
```
Unhandled Promise Rejection
Error: [1;31mError executing boot module $:/plugins/flibbles/vis-network/vis-network.min.js: "Global assignment is not allowed within modules on node."
undefined[0m
    at Object.next (C:/Users/34656/AppData/Local/tidgi/app-0.8.0-prerelease5/resources/app.asar/.webpack/main/index.js:2:1981009)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```


Thank you very much for continuing to follow up on this issue. Above is a hint that I installed the latest version of the plugin from the github repository and it still reports an error.

**Comment by linonetwo** [comment]
@flibbles You need to check the environment, like

https://github.com/tiddly-gittly/slate-write/blob/e4109acd329962f847ecc4f1749d738c92869b9b/src/widget.js#L2-L13

I check is $tw.browser before requiring the real contents

**Comment by flibbles** [comment]
I guess I did drop the ball here. Had no idea what Electron was or how to run it. (I hardly know how TiddlyMap works either.)

I've pushed a new version of [vis-network.json](https://github.com/felixhayashi/TW5-TiddlyMap/releases/tag/v0.17.16) which should have this problem resolved, though I'm not in a position to test it. @dongrentianyu will need to let me know how it goes.

**Comment by dongrentianyu** [comment]
Thank you very much for your contribution and to @linonetwo  for his work. This problem does not occur in the latest version of tidgi at the moment.

You can release a new version and CPL will then update this plugin to make it easier for other users to update the plugin.

**Comment by flibbles** [comment]
For posterity, it turns out this issue was caused not by Electron, but by changes made in TiddlyWiki V5.3.0, just in case this comes up again.
