### ISSUE TITLE
feature: 出个可以直接新建，用来测试模板的功能

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#389]
### Description 描述

大概是选定文件夹路径。然后点击按钮，给定一个编号，或者名称，这样就会直接在这里新建一个模板。这样就可以快速建很多个测试新功能用的。然后要删除的时候也可以全部都删除。

**Comment by dongrentianyu** [comment]
但感觉不出也可以。主要还是能记住之前的父文件路径才好，不然老是得从c盘调到d盘，然后一层层下去。

**Comment by linonetwo** [comment]
还是看 https://github.com/tiddly-gittly/TidGi-Desktop/issues/327 吧
