### ISSUE TITLE
bug: 第一次安装太记，某些特殊情况下，设置-编辑者署名不起作用。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#402]
### Environment 环境信息

TidGi (win64.exe)
Version v0.8.0-prerelease9.

Electron Version: 24.3.1
Node Version: 18.14.0
Chromium Version: 112.0.5615.183

### Description 描述

总结：编辑者署名似乎只能在导入wiki之前设置好才起效。倘若已经导入wiki，修改太记的编辑者署名设置则无效。
应该是仅第一次安装太记（没有太记的设置文件）并且没设置编辑者署名时导入的wiki们才可以稳定复现。
~~或者说，删除后在从新导入的wiki，问题就消失了。~~

好像修改一次编辑者署名，并且删除wiki在从新导入，问题就彻底消失了。

### Steps to Reproduce 复现方式

1. 下载太记，安装。
2. 打开太记，第一次未设置太记中的编辑者署名，直接打开wiki。
3. 在wiki打开的情况下设置太记设置里的编辑者署名为WhiteFall。重启太记，发现wiki编辑者署名 依旧为TidGi user。
4. 设置好太记的编辑者署名，然后删除wiki工作区，重新导入wiki，发现wiki编辑者署名设置成功。
5. 再次修改Wiki的太记中的编辑者署名，修改生效，问题消失。
6. 若第一次安装太记然后导入wiki，并不删除wiki，无论怎么修改太记的编辑者署名，依旧为TidGi user。

**Comment by Zacharia2** [comment]
![V}{7)ZUJKKF8@`(4GR{7@L0](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/02040f1f-7e3a-4549-8b21-53937931d758)

![G9EAFCF8{ 2`QZ1KNN9TN%H](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/a964c801-9273-4ac4-a06b-82c50bbda77d)

**Comment by Zacharia2** [comment]
Unhandled Promise Rejection
Error:  (-3) loading 'http://192.168.66.21:5215/#Index:Index'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:77647)
    at EventEmitter.failListener (node:electron/js2c/browser_init:2:77860)
    at EventEmitter.emit (node:events:525:35)

**Comment by Zacharia2** [comment]
Linux下问题相同。即只能在创建导入wiki之前设置好编辑者署名，之后设置就不起作用了。

**Comment by Zacharia2** [comment]
Linux下问题相同。

**Comment by linonetwo** [comment]
补上了要求重启的提示

**Comment by Zacharia2** [comment]
欧克克

**Comment by dongrentianyu** [comment]
呃，问题好像没有解决。在设置里会变成空白，然后填入后也确实会要求重启。但重启之后仍然是空白。不知道为什么。
