### ISSUE TITLE
bug: 拖入很大的PDF出现错误，且无法【使用open-in-external-app的工具按钮】 打开

### ISSUE THREAD

**Issue by LynnXiaoLianZi** [tiddly-gittly/TidGi-Desktop#410]
### Environment 环境信息

Windows11 

### Description 描述

安装了【$:plugins/lnonetwo/open-in-external-app】插件后，在太记中拖入拖入了一个将近1GB的PDF（高清扫描版的那种），  显示以下错误  .... teddlers文件夹下有这个文件  但显示为0kb...  ;测试2：拖入一个100多M的PDF 可以用本地阅读器打开【使用open-in-external-app的工具按钮】   tiddlers文件夹下也正常...    

![WHO2WQSXPO7WF@~FN2QQ{)R](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/5c25e9b0-78f5-464d-8438-05f375bd7d5d)

### Steps to Reproduce 复现方式

试验了几次  都是这样的 ，看看能不能解决吧。

**Comment by linonetwo** [comment]
建议安装 https://github.com/tiddly-gittly/TidGi-external-attachments-plugin 插件，在 cpl 搜这个，记得看它的网站说明
