### ISSUE TITLE
bug: 太记里面【开启于新窗口】按钮不能使用

### ISSUE THREAD

**Issue by LynnXiaoLianZi** [tiddly-gittly/TidGi-Desktop#411]
### Environment 环境信息

Windows11  太记软件桌面版  最新EXE X64版本。

### Description 描述

如下图所示，太记里面【开启于新窗口】按钮不能使用；
个人感觉这个功能还是蛮有用的，譬如使用宽屏或双屏办公的时候，可以左侧一个单独的窗口打开一个条目，右侧的屏幕就可以显示左侧条目中的引用条目，很方便。
如果有时间的话，希望也能把这个功能加上。

![ZD9N_(OYHFYFP8FSN`GZE3N](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/84c55105-0c13-456e-8498-894398ce134a)

### Steps to Reproduce 复现方式

太记里面【开启于新窗口】按钮不能使用；

**Comment by linonetwo** [comment]
最新版 0.8.0 修了
