### ISSUE TITLE
bug: 太记里面无法使用file:\\\格式直接打开外部文件或文件夹的问题。

### ISSUE THREAD

**Issue by LynnXiaoLianZi** [tiddly-gittly/TidGi-Desktop#412]
### Environment 环境信息

最新版本的太记，X64 EXE,win11

### Description 描述

看了B站上林一二的视频，照着操作，太记似乎没什么反应，测试了好多次。但是同样的语法，在TiddlyDesktop中却可以正常打开。

![WM9 LTMDO%09`@(~ RNB%`H](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/67073915-9650-4b04-8e5b-0d16bcc39cba)

### Steps to Reproduce 复现方式

太记里面无法使用file:\\\格式直接打开外部文件或文件夹的问题。

**Comment by linonetwo** [comment]
关于这个，我觉得 D:/ ，这后面估计加个 / 就好了

**Comment by linonetwo** [comment]
不过我想的是，如果太记打不开，应该弹个提示框

**Comment by LynnXiaoLianZi** [comment]
我用的[prerelease12](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.8.0-prerelease11

**Comment by LynnXiaoLianZi** [comment]
我用的时11

**Comment by linonetwo** [comment]
那应该没问题，反正可以试试加个斜杠。还有别的文件夹应该是可以的

**Comment by LynnXiaoLianZi** [comment]
![DT7I MPC%4V_IX56_0BGERW](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/95df514f-e24c-48cc-9941-5d13ef0a11b5)


又试了一下   是这样的

**Comment by LynnXiaoLianZi** [comment]
使用open会弹出这么个东西   

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/980e78e2-ea4a-4d08-85d7-17018e885c47)

**Comment by linonetwo** [comment]
斜杠反了吧，都用 /

**Comment by linonetwo** [comment]
没事，我有空用Windows电脑看看。这些功能之后都是要更新到 https://github.com/tiddly-gittly/TidGi-Official-Website 官网上变成教程的，目前还没人去更新这些

**Comment by LynnXiaoLianZi** [comment]
> 斜杠反了吧，都用 /

都试过了，两种斜杠方式在Windows电脑应该地通用的

**Comment by Zacharia2** [comment]
`[ext[文件夹|file://./tiddlers]]` 这种相对路径倒是可以。

**Comment by linonetwo** [comment]
[img[file:///var/folders/t3/0jyr287x3rd2m0b6ml8w4f2c0000gn/T/tidgi-dev/wiki/files/截屏2023-06-21 12.40.20.png]]

[[file:///var/folders/t3/0jyr287x3rd2m0b6ml8w4f2c0000gn/T/tidgi-dev/wiki/files/截屏2023-06-21 12.40.20.png]]

[[file:///var/folders/t3/0jyr287x3rd2m0b6ml8w4f2c0000gn/T/tidgi-dev/wiki/files/]]

[[file:///var/folders/t3/0jyr287x3rd2m0b6ml8w4f2c0000gn/T/tidgi-dev/wiki/files]]

[img[file://./files/截屏2023-06-21 12.40.20.png]]

[[file://./files/截屏2023-06-21 12.40.20.png]]

[[file://./files/]]

[[file://./files]]

**Comment by LynnXiaoLianZi** [comment]
新版本都已经修复好了么？ Nice!  Tks!

**Comment by linonetwo** [comment]
还在发布过程中，等等可以测试一下看看

**Comment by LynnXiaoLianZi** [comment]
OK .

**Comment by linonetwo** [comment]
在 https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.8.0-prerelease15 应该修复了

**Comment by LynnXiaoLianZi** [comment]
测试了一下绝对路径的打开（Windows11系统），结果如下：
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/abb26a84-44ce-46f4-9828-1dba61a8aebf)

能用了，总结下来：

- 打开绝对路径，如果只打开磁盘根目录，file和open格式都行；
- 打开绝对路径（任意位置），使用open的格式都可以，推荐。

---

测试了一下相对路径的打开（Windows11系统），结果如下：
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/2a06f821-da83-440d-adcf-4800d4576c69)
总结下来：

- 相对路径，访问太记工作区内部的文件夹没问题，访问外部文件夹就报错了，如上述弹窗，关闭弹窗后，太记闪退。

=======================================

---

最后，感谢您的及时响应。
PS：个人建议在发布时，或在太记教程中，将这些可能存在的小问题写在一个Attention中，以免新手拿来就用，不明所以，直接出现闪退报错，将其劝退了。

**Comment by linonetwo** [comment]
这个预发布版，所以就要靠大家来测试，之后修复了就没有问题了，才会正式发布

**Comment by linonetwo** [comment]
这些功能的介绍之后也会靠群里的志愿者更新到太极官网上

**Comment by LynnXiaoLianZi** [comment]
RE【你那个相对是啥意思？相对应该就是相对于你的文件夹，还有其他相对的意思吗？】：
是相对于我的太记文件夹啊：
如下是我的文件夹目录：

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/5c7e0d99-9332-4693-af69-f1be9b3c4eae)

下面是在太记条目的测试结果：
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/e3ab97e6-1522-435f-aa72-89683d5b8ff4)

**Comment by linonetwo** [comment]
上级目录是 ..

**Comment by LynnXiaoLianZi** [comment]
80Tidgi
 ├── 2006NumericalV527_Xp
 │   ├── plugins
 │   ├── tiddlers
 │   └── tiddlywiki.info
 ├── 2006NumericalV527_Xp.html
 ├── 2006NumericalV527_Xp.zip
 └── test

**Comment by linonetwo** [comment]
你可能没明白 .. 的用法，可以搜一下

**Comment by linonetwo** [comment]
. 是当前目录

**Comment by LynnXiaoLianZi** [comment]
我再试试😓😵

**Comment by Zacharia2** [comment]
> RE【你那个相对是啥意思？相对应该就是相对于你的文件夹，还有其他相对的意思吗？】： 是相对于我的太记文件夹啊： 如下是我的文件夹目录：
> 
> ![image](https://user-images.githubusercontent.com/52692648/247508491-5c7e0d99-9332-4693-af69-f1be9b3c4eae.png)
> 
> 下面是在太记条目的测试结果： ![image](https://user-images.githubusercontent.com/52692648/247508945-e3ab97e6-1522-435f-aa72-89683d5b8ff4.png)

Windows下没有`/`（根目录）

`. /. /`的写法似乎也是不对的。

`/. /. /xxx` 似乎也没有这样的路径

**Comment by linonetwo** [comment]
用 .. ，你去学习一下吧…问问AI也好啊

**Comment by LynnXiaoLianZi** [comment]
好的，谢谢！

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.8.0-prerelease15-fix2

用这个，没报错

**Comment by LynnXiaoLianZi** [comment]
OK!  Nice!

**Comment by linonetwo** [comment]
教程页面有了 https://tidgi.fun/#%E5%A4%AA%E8%AE%B0%E5%8A%9F%E8%83%BD%E6%89%8B%E5%86%8C%2F%E5%BC%95%E7%94%A8%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6
