### ISSUE TITLE
bug: 自动同步后需要重启

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#416]
### Environment 环境信息

Version v0.8.0-prerelease9.

Electron Version: 24.3.1
Node Version: 18.14.0
Chromium Version: 112.0.5615.183

### Description 描述

大概就是太记自动同步之后需要重启wiki。具体可见下面的图片。我觉得这个可以解决一下。

### Steps to Reproduce 复现方式

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/b935850d-47e5-490c-a234-31d451d8c68f)

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/e7be6279-0a15-4a5b-b3e4-b19759c19d29)

**Comment by dongrentianyu** [comment]
但又感觉不像是同步影响的。太记刚才自动同步了，但没出现上面的问题。不知道为什么。

**Comment by linonetwo** [comment]
一般会自动重启的，不过截图这个不知道怎么搞出来的

**Comment by dongrentianyu** [comment]
有时会自动重启，有时不会。不过也有可能是因为电脑了睡眠了，然后我再打开，就不会重启。或者我有一段时间没用太记，可能半小时左右，然后就会出现这种情况了。

**Comment by dongrentianyu** [comment]
不过确实也不是什么大问题。

**Comment by linonetwo** [comment]
要是有一下子就能复现的稳定方法就可以修复了。

**Comment by linonetwo** [comment]
不过先别折腾这个了，之后可能要取消这个设定。
