### ISSUE TITLE
bug: Tiddlers that are modified by external applications cannot be synced and rendered immediately

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#418]
### Environment 环境信息

no

### Description 描述

Tiddlers that are modified by external applications cannot be synced and rendered immediately. Moreover, if I further edit them with TiddlyWiki, the earlier modifications will be lost. This often leads me to restart TidGi for maintaining consistency between the contents. The entire process is quite laborious.

Perhaps, a mechanism similar to HMR in frontend can be integrated to ensure synchronization between local tiddler files and the current contents within the app.

I am particularly fond of the 'Open In External App' plugin since I prefer editing tiddlers (mostly in Markdown) with Typro.

### Steps to Reproduce 复现方式

no

### Additional Context 额外上下文

no

**Comment by linonetwo** [comment]
Try https://github.com/tiddly-gittly/watch-fs

You can report bug there, it still need sone test before I announce it in the talk forum...

**Comment by linonetwo** [comment]
And you can try "restart service" in the context menu to do a full-reload at any time.

**Comment by heavenkiller2018** [comment]
It effecs on restarting the service, which takes approximately 20 seconds to complete.

**Comment by linonetwo** [comment]
you mean watch-fs? You can create reproduce and rise issue there.

On my side it doesn't slow like this.
