### ISSUE TITLE
feature: A web extension integrating bookmarks could be developed to enhance TidGi

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#419]
### Description 描述

A web extension could be developed to enhance the application of TidGi in knowledge management, for instance, integrating bookmarks, such as pinbox. Connecting TidGi with the internet via the web extension would lead to even greater possibilities.

It would be especially wonderful if TidGi provided us with the opportunity to reduce usage of certain applications and integrate related ones, particularly in the areas of knowledge management and note-taking.

**Comment by linonetwo** [comment]
Well, these features requests are common, tw is 10+ years old. So you can always find these requests in talk forum, you can try search there.

But there is a WIP in https://github.com/mika-cn/maoxian-web-clipper/pull/172 and https://github.com/tiddly-gittly/Maoxian-Webclipper-Tiddlywiki-Addon , If you know Javascript you can try contribute!
