### ISSUE TITLE
bug: 云端同步后会弹出github错误窗口

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#426]
### Environment 环境信息

TidGi (win32)
Version v0.8.0.

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Description 描述

把本地工作区设置为云端工作区之后，每半小时同步一次。同步之后就会弹出下面图片的报错。虽然点确定就没什么问题了，数据也不会丢失，但老是弹，就很烦。

### Steps to Reproduce 复现方式

本地工作设置成云端。新建一个条目。感觉之前就有这个问题，但好像一直没有得到解决。还是说我设置出了问题。我设置基本上如下面图片所示。

### Additional Context 额外上下文

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/8bc0ac2b-7dfa-4682-bfdd-d150b13b739e)

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/76cf6e9c-c3c4-476d-a16d-10d58ebb61e0)

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/584b8f27-2229-4f83-9135-ed12663a7264)

**Comment by dongrentianyu** [comment]
是因为我同时打开了github desktop吗？

**Comment by dongrentianyu** [comment]
好像确实是因为github desktop同时打开然后受影响。我猜测是因为太记的git操作和github desktop的git操作冲突了。

**Comment by linonetwo** [comment]
这样子吗？我一般以为是被墙了。

下次要不把 log 发来看看，里面有写具体情况

**Comment by dongrentianyu** [comment]
现在的问题是，不弹出窗口了，但不同步。这就很麻烦了。我还搞不清楚这个不同步是怎么一回事。是github desktop影响了，还是梯子影响了，还是因为我时常会两者之间切换影响了。

**Comment by dongrentianyu** [comment]
不管是公开的wiki还是私密的wiki都是没有自动同步，除非我退出太记，重新打开太记。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/a4f0053f-332d-405c-9198-9ba43e7741c6)

比如这个条目刚好是五点编辑的。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/08cf850c-c63e-485d-be1f-70cb54587a5e)

我设置的同步是15分钟。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/d6e19d23-1c04-491e-9a75-35f8e12aef66)

在仓库这边也有设置成云端然后同步。

目前是开了梯子，也打开github desktop。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/a3bad1fa-40d7-49c2-b900-507bc4afccde)


而过去十五分钟后还是没有同步。我再等一等看看。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/aef059bc-f8c1-4740-a033-2b4600c0a8df)

过了半小时仍然没有自动同步上去。

 
[error-IFuB2i9Q72DX2E5H_lKdW-WENAI-2023-06-26.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/11866751/error-IFuB2i9Q72DX2E5H_lKdW-WENAI-2023-06-26.log)

还有一个json文件。上传不过来，我就直接把代码复制过来了。

```json
{
    "keep": {
        "days": true,
        "amount": 14
    },
    "auditLog": "C:\\Users\\34656\\AppData\\Roaming\\TidGi\\logs\\.110dab839f6d0b7a86e93dd52adb40cc7faaf62b-audit.json",
    "files": [
        {
            "date": 1687628193613,
            "name": "C:\\Users\\34656\\AppData\\Roaming\\TidGi\\logs\\error-IFuB2i9Q72DX2E5H_lKdW-WENAI-2023-06-25.log",
            "hash": "a6fb1745228d35b50c90516e8d07e1c2a27ccbbd348f26f52e3b1ad0c40fdf3a"
        },
        {
            "date": 1687749983738,
            "name": "C:\\Users\\34656\\AppData\\Roaming\\TidGi\\logs\\error-IFuB2i9Q72DX2E5H_lKdW-WENAI-2023-06-26.log",
            "hash": "02fa6f890ce297c2011ec99a52bd7eb03b1873cba442d1d96b084096db5a3c52"
        }
    ],
    "hashType": "sha256"
}
```

**Comment by dongrentianyu** [comment]
[-8tUM6VYKmEDDiIXhFGyR-BMF-2023-06-26.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/11866878/-8tUM6VYKmEDDiIXhFGyR-BMF-2023-06-26.log)

这个应该是最新的，但不知道为什么刚才上传时没显示出来。

**Comment by dongrentianyu** [comment]
在太记同步之前，我打开了github desktop。

本来我想把不能正常同步和同步时报错分成两个issue，但一想这两个是为了解决同一个问题，就没分开来。

**Comment by linonetwo** [comment]
它就是说 Connection was reset ，意思就是墙了

**Comment by dongrentianyu** [comment]
那这样的话，就不好解决了。我查了一下，有些文章说是因为开了vpn影响的，但不开vpn能正常同步吗？不过现在不开也要开了，现在做很多事情都要开vpn。不开反而影响正常学习工作。

**Comment by linonetwo** [comment]
改成弹 wiki 内提示了，这样就不会弹框了

**Comment by linonetwo** [comment]
你可以搜搜 git 没走 vpn 是为什么，我用shadowsocks所以我没这个问题

**Comment by dongrentianyu** [comment]
这个大概查了一下，就是代理有两种方式，一种是走http代理的，一种是走ssh代理的。我用vpn可能走的是http代理。你的可能走的是ssh代理。研究起来有点复杂，还是先不管了。

**Comment by linonetwo** [comment]
反正至少现在不弹框了吧

**Comment by dongrentianyu** [comment]
但好像只有本地的会过半小时同步一次，而云端的不会过半小时同步推上去一次。

**Comment by dongrentianyu** [comment]
比较迷，有时可以同步，有时同步不上。可能还是因为墙的原因。

**Comment by dongrentianyu** [comment]
不过改成在wiki内弹窗确实比较好。打开wiki显示一下就没了。

**Comment by linonetwo** [comment]
同步不上，实际看LOG会说他被墙了，其实是有每半小时执行一次，只是失败了而已
