### ISSUE TITLE
bug: 侧边栏右键工作区用浏览器打开失效

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#429]
### Environment 环境信息

Version v0.8.0.

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Steps to Reproduce 复现方式

侧边栏 - 右键 - 用浏览器打开，点击后无响应。

**Comment by linonetwo** [comment]
得打开 HTTP 服务器功能才能用它，不过我觉得在这种情况下可以让它点击了自动跳到设置那边。

**Comment by Zacharia2** [comment]
我启用了 HTTP API ，，并且浏览器可以正常访问。我还关闭了鉴权凭证。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/42fc135d-4115-4222-a4f4-f2cd19107320)

**Comment by linonetwo** [comment]
那看来是有点问题

**Comment by Zacharia2** [comment]
debug查看发现actualIP实际为` tidgi://Y75eKVCYXLI9cEeye2TY0:5212 `

https://github.com/tiddly-gittly/TidGi-Desktop/blob/592f60d2c091763f201d6630c3d2666a037200f2/src/services/workspaces/getWorkspaceMenuTemplate.ts#L103-L104
