### ISSUE TITLE
bug: 开机自启动加载wiki失败以及版本错乱

### ISSUE THREAD

**Issue by on-in-i** [tiddly-gittly/TidGi-Desktop#436]
### Environment 环境信息

Version v0.8.1-prerelease1

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Description 描述

安装Windows-x64 v0.8.1-prerelease1，然后打开开机自启动，重启电脑，TigGi开机自启动会加载wiki失败，以及显示有新版本，当前版本显示为Version v0.7.14

![2023-07-06_00004](https://github.com/tiddly-gittly/TidGi-Desktop/assets/100055123/68c2ab4f-2a2c-4490-978a-28e72f24a45c)

此时关闭TidGi再打开，加载wiki成功，不再提示有新版本，版本显示正常。

![2023-07-06_00005](https://github.com/tiddly-gittly/TidGi-Desktop/assets/100055123/10a85019-3df7-4fc4-8166-3d2d7ccd25ce)

### Steps to Reproduce 复现方式

安装Windows-x64 v0.8.1-prerelease1，然后打开开机自启动，之后每一次开机自启动都会重复加载wiki失败和版本错乱。

**Comment by linonetwo** [comment]
估计同时装了 msi 和 exe 版本的吧

**Comment by on-in-i** [comment]
啊确实是这样，哈哈没注意，卸载了另一个 msi 版本的太记后正常了。
