### ISSUE TITLE
bug: github actions 配置pages 报错 node环境id不合法 

### ISSUE THREAD

**Issue by HyjHyper** [tiddly-gittly/TidGi-Desktop#437]
### Environment 环境信息

TidGi (win32)
Version v0.8.0.

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

但错误发生在 github 上

### Description 描述

github actions 配置报错
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/76864800/ec2ebc6c-878c-4497-a47c-f3774385d8b6)
提示：Error: HttpError: Invalid environment node id. 

### Steps to Reproduce 复现方式

本人使用自带同步总是出错，所以选择使用github desktop单独上传，上传之后，actions就会出错。重复运行，报错重复。

### Additional Context 额外上下文

个人认为是Actions配置文件过时或者错误了，但由于自己对这方面的代码了解甚少，特来求助。

**Comment by on-in-i** [comment]
1. 只需要备份而不部署在网站或博客的话，可以这样做
    - 这是一个文件路径：`（你的wiki仓库文件夹）\.github\workflows\gh-pages.yml`
    - 编辑`gh-pages.yml`

> 将其中的
> ```
>       - name: Deploy to GitHub Pages
>         id: deployment
>         uses: actions/deploy-pages@v1
> ```
> 改为
> ```
> #      - name: Deploy to GitHub Pages
> #        id: deployment
> #        uses: actions/deploy-pages@v1
> ```
> 即注释掉这段代码，作用是取消了 `Deploy to GitHub Pages` 这个步骤。


2. 需要部署网站或博客的话，尝试参考`https://www.bilibili.com/video/BV1uD4y1H7ri/`这个视频。

**Comment by linonetwo** [comment]
可以尝试从 https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template 复制最新版 Action 、 package json，可能有更新。现在用它初始化的一般直接就能用了。
