### ISSUE TITLE
bug: 日志文件非常大

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#441]
### Environment 环境信息

TidGi (win32)
Version v0.8.1-prerelease1

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Steps to Reproduce 复现方式

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/4ff7b038-e1e2-4962-815e-bf61c2d22040)

**Comment by linonetwo** [comment]
会定期自动删除的，不过你可以打开看看主要重复的都是什么内容。 为什么那天那么大

**Comment by Zacharia2** [comment]
okkk
