### ISSUE TITLE
bug: 该路径不存在 "\myblog\Wiki"

### ISSUE THREAD

**Issue by C-LiYang** [tiddly-gittly/TidGi-Desktop#443]
## Environment

TidGi 0.8.0
Electron 25.2.0
win32 10.0.22621
Locale: zh-CN

## Additional Context

```typescript
Error: 该路径不存在 "\myblog\Wiki"
```

---

**Comment by linonetwo** [comment]
Steps to Reproduce:

**Comment by C-LiYang** [comment]
在导入线上github公开的空的仓库，
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/60461897/f0ef3c73-d0a8-4c9d-a231-112617fee63a)
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/60461897/23b24375-09fa-4d9a-bed9-c6600495149a)

**Comment by linonetwo** [comment]
传个log

**Comment by linonetwo** [comment]
空的啊，不能空的

**Comment by C-LiYang** [comment]
> 

我是要先创建一个本地的文件夹吗？
我是按照这个来的 
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/60461897/d514b25c-8ae6-476c-b56a-3e9649672982)

**Comment by linonetwo** [comment]
那个不是太记的教程，你得跟着太记里的提示来，先把Github上的删了，然后在太记里创建本地的，之后右键工作区图标在工作区设置里打开变成在线工作区，然后通过太记创建线上工作区

**Comment by linonetwo** [comment]
可以试试最新预发布版
