### ISSUE TITLE
bug: 工作区自定义图标后，下次加载就无法显示了，只能重新加载一个本地图片

### ISSUE THREAD

**Issue by LynnXiaoLianZi** [tiddly-gittly/TidGi-Desktop#445]
### Environment 环境信息

太记版本，最新的【Install-TidGi-Windows-x64-v0.8.1-prerelease1.exe】

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52692648/4a2fe2ae-02b4-46d2-a1f3-f78a2ff54068)

---
而且，加载了本地图片后，不能点保存，一点就又没了。不点还行，但退出太记，下次加载图标又没了。

### Description 描述

如上所述。

### Steps to Reproduce 复现方式

如上所述。

### Additional Context 额外上下文

小问题，有个自定义工作区图标看着舒服些。

**Comment by linonetwo** [comment]
试试最新预发布版，应该没问题了，至少mac上没问题
