### ISSUE TITLE
bug: Could not find executable for 'GitHub Desktop' at path '~/Downloads/GitHub Desktop.app

### ISSUE THREAD

**Issue by xushaobo** [tiddly-gittly/TidGi-Desktop#447]
Mac下GiHub Desktop.app默认安装在 /Applications 目录下，在太记中用打开git 可视化报错在 ~/Downloads 目录下找不到 app，应该在哪设置路径，没有看到。另外外部编辑器现在默认是打开vsc，怎么设置其它编辑器

**Comment by linonetwo** [comment]
应该是因为没有装 GitHub Desktop 吧

> 怎么设置其它编辑器

这个应该是改 src/services/native/index.ts 里的 openInEditor，有空可以来 PR
