### ISSUE TITLE
bug: tiddler bar无法和已打开的条目关联

### ISSUE THREAD

**Issue by chxp2008** [tiddly-gittly/TidGi-Desktop#449]
### Description 描述

点击横条已打开条目按钮，在tw里面会打开相同的条目，相当于打开了两个相同的条目。点击关闭按钮会关闭第二个打开的相同条目。

### Steps to Reproduce 复现方式

安装opened tiddler bar复现

**Comment by linonetwo** [comment]
太记默认创建的会这样？

**Comment by chxp2008** [comment]
不是默认创建的，之前怀疑是和某个插件冲突，删除了所有插件还是有相同问题。现在怀疑是修改了某个系统条目导致的冲突。

**Comment by linonetwo** [comment]
搞不定这些的话，建议只使用太记默认创建的模板。
