### ISSUE TITLE
bug: Unexpected non-whitespace character after JSON at position 1231

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#452]
### Environment 环境信息

TidGi (win32)
Version v0.8.1-prerelease4

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Description 描述

Unhandled Promise Rejection
SyntaxError: Unexpected non-whitespace character after JSON at position 1231
    at JSON.parse (<anonymous>)
    at C:/Users/Snowy/AppData/Local/tidgi/app-0.8.1-prerelease4/resources/app.asar/.webpack/main/index.js:2:155441
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

### Steps to Reproduce 复现方式

- 卸载太记并清除所有相关文件，重新安装。

- 在导引中输入默认编辑者署名，点击空白处。

问题复现。

[TidGi-2023-07-18.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/12081713/TidGi-2023-07-18.log)

**Comment by Zacharia2** [comment]
#402 类似

**Comment by linonetwo** [comment]
你看看 C:/Users/Snowy/AppData/Local/tidgi/app-0.8.1-prerelease4/resources/app.asar/.webpack/main/index.js:2:155441 这行是什么？

**Comment by Zacharia2** [comment]
这好像没法看啊，解压这个文件后得到的index.js也是经过压缩和混淆后的。

**Comment by Zacharia2** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/442a0932-41c6-415c-88e5-0cb29f91efac)


大概是这样的。

**Comment by linonetwo** [comment]
vscode 可以 ctrl + p 然后 :2:155441 跳转呀

**Comment by Zacharia2** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/13620571-1c8f-43f3-b428-d4cdcf3afadb)

**Comment by Zacharia2** [comment]
大概是这样的
