### ISSUE TITLE
bug: E-13 维基运行时有错误

### ISSUE THREAD

**Issue by Rac0lW** [tiddly-gittly/TidGi-Desktop#456]
### Environment 环境信息

E-13 维基运行时有错误，原因请查看 log 文件，并上传提交 issue 以便修复。

{"type":"running","uid":6,"resultType":"observable"}
{"type":"result","uid":6,"payload":{"type":"control","actions":"tw-start"}}
{"type":"result","uid":6,"payload":{"type":"control","source":"intercept","actions":"tw-error","message":"\u001b[1;31mError executing boot module $:/plugins/kixam/datepicker/widget.datepicker.js: {\"code\":\"MODULE_NOT_FOUND\",\"requireStack\":[\"C:\\\\Users\\\\racol\\\\AppData\\\\Local\\\\TidGi\\\\app-0.7.14\\\\resources\\\\node_modules\\\\@tiddlygit\\\\tiddlywiki\\\\boot\\\\boot.js\",\"C:\\\\Users\\\\racol\\\\AppData\\\\Local\\\\TidGi\\\\app-0.7.14\\\\resources\\\\app.asar.unpacked\\\\.webpack\\\\main\\\\543.index.worker.js\"]}\n\nnode:internal/modules/cjs/loader:966\n  throw err;\n  ^\n\nError: Cannot find module '$:/plugins/kixam/moment/moment.js'\nRequire stack:\n- C:\\Users\\racol\\AppData\\Local\\TidGi\\app-0.7.14\\resources\\node_modules\\@tiddlygit\\tiddlywiki\\boot\\boot.js\n- C:\\Users\\racol\\AppData\\Local\\TidGi\\app-0.7.14\\resources\\app.asar.unpacked\\.webpack\\main\\543.index.worker.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:963:15)\n    at Module._load (node:internal/modules/cjs/loader:811:27)\n    at Function.f._load (node:electron/js2c/asar_bundle:2:13328)\n    at Module.require (node:internal/modules/cjs/loader:1035:19)\n    at c (C:\\Users\\racol\\AppData\\Local\\TidGi\\app-0.7.14\\resources\\app.asar.unpacked\\.webpack\\main\\543.index.worker.js:2:295396)\n    at Object.$tw.modules.execute (C:\\Users\\racol\\AppData\\Local\\TidGi\\app-0.7.14\\resources\\node_modules\\@tiddlygit\\tiddlywiki\\boot\\boot.js:867:11)\n    at require (C:\\Users\\racol\\AppData\\Local\\TidGi\\app-0.7.14\\resources\\node_modules\\@tiddlygit\\tiddlywiki\\boot\\boot.js:826:24)\n    at $:/plugins/kixam/datepicker/widget.datepicker.js:22:16\n    at $:/plugins/kixam/datepicker/widget.datepicker.js:241:1\n    at Script.runInContext (node:vm:141:12)\u001b[0m\n"}}

### Description 描述

搭载TiddlyWiki的主机以及连接它的交换机 被人碰到电源后关闭又重启了（我也不知道他干了什么，我的远程主机就重启了，同时网络也断了），之后无论从网页上还是主机上的Tidgi都无法打开笔记了，保存的三个笔记库全部无法打开，文件使用了Google Drive备份和Synology idrive备份，恢复了昨天的版本后依然无法打开。

发生这件事情时，正使用Safari浏览器 访问该笔记库，并有草稿，但是此时电脑在另外一个窗口。

### Steps to Reproduce 复现方式

这个我也不知道怎么复现，主机被重启了，就发生了这样的事情。

重新建立笔记，将原有的tiddlers文件复制到新建立的笔记文件里面，会重新出现次问题。

该文件夹内最后一个文件是 $_StoryList.tid

**Comment by Rac0lW** [comment]
Unhandled Promise Rejection
Error: [1;31mError executing boot module $:/plugins/kixam/datepicker/widget.datepicker.js: {"code":"MODULE_NOT_FOUND","requireStack":["C://Users//racol//AppData//Local//TidGi//app-0.7.14//resources//node_modules//@tiddlygit//tiddlywiki//boot//boot.js","C://Users//racol//AppData//Local//TidGi//app-0.7.14//resources//app.asar.unpacked//.webpack//main//543.index.worker.js"]}
node:internal/modules/cjs/loader:966
  throw err;
  ^
Error: Cannot find module '$:/plugins/kixam/moment/moment.js'
Require stack:
- C:/Users/racol/AppData/Local/TidGi/app-0.7.14/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js
- C:/Users/racol/AppData/Local/TidGi/app-0.7.14/resources/app.asar.unpacked/.webpack/main/543.index.worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at c (C:/Users/racol/AppData/Local/TidGi/app-0.7.14/resources/app.asar.unpacked/.webpack/main/543.index.worker.js:2:295396)
    at Object.$tw.modules.execute (C:/Users/racol/AppData/Local/TidGi/app-0.7.14/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:867:11)
    at require (C:/Users/racol/AppData/Local/TidGi/app-0.7.14/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:826:24)
    at $:/plugins/kixam/datepicker/widget.datepicker.js:22:16
    at $:/plugins/kixam/datepicker/widget.datepicker.js:241:1
    at Script.runInContext (node:vm:141:12)[0m
    at Object.next (C:/Users/racol/AppData/Local/TidGi/app-0.7.14/resources/app.asar/.webpack/main/index.js:2:1710205)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by linonetwo** [comment]
你看它说是 $:/plugins/kixam/datepicker/widget.datepicker.js 这个插件报错了，缺这个插件  Error: Cannot find module '$:/plugins/kixam/moment/moment.js'

这种小问题群里问问，尤其是问机器人就好了。

**Comment by linonetwo** [comment]
无端重启可能是服务器被黑了

**Comment by Rac0lW** [comment]
感谢解答，第一次使用github的issues功能，有点草率了，请见谅。

我下载了最新版TidGi 就解决了这个问题。

我又试了一些操作，我觉得可以复现了这个问题了。

使用0.7.14版本，新建立一个工作区，并更新插件（使用）：设置->获取更多插件->太微中文社区插件源（Github版），并自动更新所有插件（显示有47个插件需要更新），并重启服务就会出现这个问题。

**Comment by linonetwo** [comment]
总之就是缺少了某个插件，就算是在旧版上，只要安装缺失的插件也能解决，这主要是他微核心现在还不支持递归多层安装，依赖的依赖，还有依赖的依赖的依赖，这个官方那边有个一修哦，感兴趣可以看一看，反正还等待开发者来解决
