### ISSUE TITLE
feature: Can the TidGi External Attachments Plugin support the use of relative yet absolute paths?

### ISSUE THREAD

**Issue by heavenkiller2018** [tiddly-gittly/TidGi-Desktop#458]
### Description 描述

Can the TidGi External Attachments Plugin support the use of relative yet absolute paths? The latter may hinder portability. For instance, I encountered an issue when attempting to modify the _canonical_uri field of an imported PDF file. I tried changing it from "file:///C:/Users/11507/Dropbox/TidGi-Desktop-Repo/Computer-Science/files/test.pdf" to "file:///../files/test.pdf," but was unsuccessful.

**Comment by linonetwo** [comment]
file://../files

**Comment by heavenkiller2018** [comment]
Some Issues:

1. The uploaded PDF file is not displaying correctly.
![Screenshot 2023-07-27 103400](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45555611/862f33e6-ef45-4ae8-a7bb-7ba6f7f9b696)

2. The uploaded MP4 file is not playing properly.
![Screenshot 2023-07-27 103305](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45555611/4bed1c59-0656-4fa7-b3f6-ade56da4315f)

3. When I upload an .flac file(about 30MB), TidGi perceives it as a text tiddler, causing the system to slow down even crash down significantly.

Which file types are supported by this plugin for importing as "skinny tiddlers"?

I have a few suggestions to enhance this plugin's functionality in handling files:

1. Portability: When dragging an external file into TidGi, it should be saved in a specified directory within the wiki, such as '../files', and named using a hash of its content(for Uniqueness). The original filename should be stored in a designated field called 'original_filename'. The '_canonical_uri' field should be set as a relative path rather than an absolute path, like "file://../files/test.pdf".

2. When opening the generated tiddler, it should be rendered according to its filetype so that it can be directly interacted with. For example, a PDF file can be viewed, and an MP4 file can be played.
Alongside the "Open In External App" functionality, these tiddlers with the '_canonical_uri' field should be opened by an external application based on their original filetype, rather than the extension of the tiddler itself, which merely serves as a pointer.

3. An export function should be provided for these '_canonical_uri' tiddlers.

If the above proposals are implemented, I would be able to utilize TidGi to conviniently and effectively manage most of my PC files, such as PDFs, MP4s, and MP3s, instead of relying solely on the Windows File Explorer, as TidGi surpasses it in searching and information management capabilities. It is currently limited to handling solely text-based file formats.

**Comment by linonetwo** [comment]
https://talk.tiddlywiki.org/t/about-the-file-uploads-plugin/19

**Comment by heavenkiller2018** [comment]
@linonetwo 

For TidGi-Desktop,I have explored alternative solutions, excluding Fission and Github. The remaining options, namely PUT, Node.js, and Webdav, seemly, none of them proved successful. And the option for "Node.js files PUT uploader support" is not even displayed in the available configuration choices of "File Uploads". Is there a viable "File Uploads" solution available for TidGi-Desktop? Additionally, it seems that the feature of "File Uploads" may potentially clash with the functionality provided by the "External Attachments for TidGi" application.


WebDAV

```
WebDAV-LS - 28th July 2023 at 8:22am
Error: Could not retrieve the contents of the directory /.

Failed to execute 'fetch' on 'Window': Failed to parse URL from /
```



PUT-uploader

```
PUT-uploader - 28th July 2023 at 8:39am (count: 2)
Error saving file test1.pdf: TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from files/test1.pdf
```

**Comment by linonetwo** [comment]
> feature of "File Uploads" may potentially clash with the functionality provided by the "External Attachments for TidGi"

Report there for him, maybe he knows

**Comment by linonetwo** [comment]
Here is the doc https://tidgi.fun/#TidGi%20Feature%20Handbook%2FReference%20External%20Files about this
