### ISSUE TITLE
feature: 设置打开软件时启动的wiki

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#463]
### Description 描述

还是因为有很多个wiki，然后打开软件后，需要手动去启动每个wiki。

如果能够设置一下，在开机时，启动那些wiki，这样感觉就会好一点。

**Comment by linonetwo** [comment]
没有休眠，就都会启动呀，你可以通过浏览器打开，就知道它们已经启动了

**Comment by dongrentianyu** [comment]
我完全关闭软件后，再重新打开软件就会发现所有wiki都进入了休眠状态，需要重新点击并等待十几秒启动。而且每个wiki都需要再点击再启动。

如果只是简单退出，但还在后台开着，那没有影响。

**Comment by linonetwo** [comment]
你是不是开了工作区休眠

**Comment by dongrentianyu** [comment]
没有啊，基本上没开休眠。

**Comment by dongrentianyu** [comment]
https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/9d323de4-051c-4723-a5cb-68988f302a36

简单录了个视频，大概就是退出之后，再重新进入会需要再启动wiki。

**Comment by dongrentianyu** [comment]
糟糕，没注意把音乐也录进去了。尴尬。

**Comment by linonetwo** [comment]
变成灰色说明是休眠了，一般不休眠的都是黑色的

**Comment by linonetwo** [comment]
你看工作区设置、全局设置等等

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/0cb14282-5d0a-4f74-a652-932917fa7f7f)

原来是在性能这里。之前一直是开着的。现在退出软件再启动，只会对最后使用的那个wiki进行重启，其他wiki不需要重启了。
