### ISSUE TITLE
bug: 在tidgi中登录github后仍然展示未登录

### ISSUE THREAD

**Issue by CapZhang** [tiddly-gittly/TidGi-Desktop#464]
## Environment

TidGi 0.8.0
Electron 25.2.0
darwin 21.6.0
Locale: zh-CN

## Steps to Reproduce:
1. 点击导入线上库
2. 点击登录github
3. 登录后仍然展示未登录

## Additional Context

```typescript
Error: 未登录
```

---

**Comment by linonetwo** [comment]
那个不能用的话，你先手动领取一个token，甜到这边吧。那个登录按钮应该得找时间换掉。不过我是没时间，就看有没有其他人想搞。

**Comment by linonetwo** [comment]
下个版本改成 Github 官方登录了

**Comment by sisyphus1212** [comment]
> 那个不能用的话，你先手动领取一个token，甜到这边吧。那个登录按钮应该得找时间换掉。不过我是没时间，就看有没有其他人想搞。
我手动填写了token也同步不了
