### ISSUE TITLE
bug: 拖入插件后，重启服务，报错

### ISSUE THREAD

**Issue by HushHorizon** [tiddly-gittly/TidGi-Desktop#477]
### Environment 环境信息

TidGi (win32)
Version v0.8.1-prerelease6

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Description 描述

这是一个tiddlywiki插件网址：`https://bimlas.gitlab.io/tw5-highlight-searched-text/`

在此插件网址中把该插件拖入`TidGi-Desktop`的默认wiki模板后，重启服务报错。

但是，把相同的默认wiki模板导出为单文件HTML后，拖入该插件可以正常使用。即使这样，把已经拖入插件的单文件HTML再用`TidGi-Desktop`打开，依旧报错。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/100055123/0901d249-7ff4-4199-b8f2-9ef2a2a32a66)

### Steps to Reproduce 复现方式

在`TidGi-Desktop`新建wiki，在此插件网址`https://bimlas.gitlab.io/tw5-highlight-searched-text/`中，把该插件拖入wiki，重启服务，报错。

**Comment by linonetwo** [comment]
https://groups.google.com/g/TiddlyWiki/c/yPsOEm4quZY

这个是太微核心更新后，有的老插件也得更新了，这个估计作者自己也没用了，没更新

**Comment by HushHorizon** [comment]
好吧，确实是很久不更新的老插件，还是应该在安卓app上增加搜索功能，继续钻研去了。
