### ISSUE TITLE
bug: 使用单文件 wiki.html 导入太记后无法使用官方插件库

### ISSUE THREAD

**Issue by teteko233** [tiddly-gittly/TidGi-Desktop#486]
### Environment 环境信息

OS: Windows 10 Home Edition
TidGi: v0.8.1-prerelease6
TiddlyWiki: 5.3.0-prerelease-2023-06-30

proxy: ping www.google.com  time <1ms
Locale: zh-CN

### Description 描述

![screenshot](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52707233/444b006a-5b4e-4533-85a3-3f33fc11c4c0)

### Steps to Reproduce 复现方式

随便找个单文档 wiki，导入太记中，我这里用的是空模板，然后保存重启服务，发现无法加载官方插件库

**Comment by linonetwo** [comment]
是的，所以建议用太记默认的。

你装个 CPL，有官方插件

**Comment by linonetwo** [comment]
或者 Itonnote 插件里也有官方插件源

**Comment by teteko233** [comment]
所以这是一项 feature 而非 bug 对吗？

**Comment by linonetwo** [comment]
是的，杰里米故意隐藏的，具体看官方仓库 issue
