### ISSUE TITLE
feature: 多wiki全局搜索

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#487]
### Description 描述

因为wiki很多，有时一个小条目，不知道记在哪个wiki里了。感觉可以搞一个多wiki全局搜索，这样我就不用打开everything这种软件来搜索了。然后点击可以跳转过去。

我看好像已经有做了一个搜索框，但好像搜索不出来内容。哦，那个好像是快速添加条目的。

**Comment by linonetwo** [comment]
最好还是用搜索框，例如 [rubick](https://github.com/rubickCenter/rubick)，然后写个插件接个API来搜，就像 https://openuserjs.org/scripts/linonetwo/TiddlyWiki5_Combine_TW5_and_search_engine_results ，是可以搜所有 wiki 的

**Comment by dongrentianyu** [comment]
哈哈，刚看到rubick的知乎推文，这就去试试

**Comment by dongrentianyu** [comment]
但感觉只能搜索到标题，要是能够搜索到正文，那就更好了。

**Comment by linonetwo** [comment]
关键还是提供 tidgi:// 这种链接，这样就可以用 rubick 打开了。如果在太记里做其实就是把 rubick 整合进来，这个有人 PR 我也接受

**Comment by dongrentianyu** [comment]
rubick没用明白，主要是觉得如果我只用这一个功能的话，为什么不用everything呢？后面我就用了另一款免费软件，Anytxt，这个也挺好用。就是需要把一些不需要建立索引的文件夹给取消掉，然后新建一个tid格式，就基本上可以正常搜索了。搜索起来也快，也支持预览。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/9b7aba52-b4a3-4324-afe2-51701a59db56)


当然最好的还是直接在太记里搜索。 

rubick主要是我觉得定位比较尴尬，功能不够多，所以很多提供在线工具的网站可以代替里面大多数功能。而涉及到本地内容的，quicker也可以代替大多数功能。可能在mac上会更好用？不太清楚。

**Comment by linonetwo** [comment]
主要是写插件调用太微的api，而不是直接搜硬盘上文本

**Comment by linonetwo** [comment]
可以配合 https://talk.tidgi.fun/topic/192/ 搜索所有工作区
