### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by rushfly** [tiddly-gittly/TidGi-Desktop#492]
### Environment 环境信息

TidGi (win32)
Version v0.8.0.

Electron Version: 25.2.0
Node Version: 18.15.0
Chromium Version: 114.0.5735.134

### Description 描述

插件更新重启后变为未更新前状态

### Steps to Reproduce 复现方式

插件更新后（比如itonnote），保存刷新页面，插件正常生效，然后重新启动，提示需要更新，查看插件版本是未更新前的。

**Comment by linonetwo** [comment]
可以搜索中文教程 https://tw-cn.cpolar.top/#%E6%8F%92%E4%BB%B6%E6%9B%B4%E6%96%B0%E5%90%8E%E9%87%8D%E5%90%AF%E5%8F%88%E8%A6%81%https://tw-cn.cpolar.top/#%E6%8F%92%E4%BB%B6%E6%9B%B4%E6%96%B0%E5%90%8E%E9%87%8D%E5%90%AF%E5%8F%88%E8%A6%81%E6%9B%B4%E6%96%B0E6%9B%B4%E6%96%B0

**Comment by rushfly** [comment]
完全删除后重新安装就没问题了。
