### ISSUE TITLE
bug: 历史菜单栏显示异常。无限个循环历史。

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TidGi-Desktop#496]
### Description 描述

历史菜单栏全是无限个没有用的东东。

### Steps to Reproduce 复现方式

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/32425955/a171aebf-6a57-4ff8-b46f-4caf10f2ae59)

**Comment by linonetwo** [comment]
最新版已修复
