### ISSUE TITLE
bug: github email无法保存下来

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#501]
### Environment 环境信息

TidGi (win32)
Version v0.9.0-prerelease3

Electron Version: 28.1.0
Node Version: 18.18.2
Chromium Version: 120.0.6099.109

### Description 描述

在设置中填写了github邮箱，但是一重启就没了。

### Steps to Reproduce 复现方式

在设置里填写github邮箱。重启应用，邮箱空白。

### Additional Context 额外上下文

纯数字邮箱和英文邮箱都试过了，在setting文件里，会保存一下。但重启后又变成null了。

编辑者姓名倒是保存下去了。不会变成null了。

token也不会影响github desktop了。那边issue也关闭了，我重新提一个issue来追踪这个问题。避免产生混乱。

**Comment by linonetwo** [comment]
你清空log之后，保存一下看看log，现在保存应该会在log里有体现了

**Comment by dongrentianyu** [comment]
[TidGi-2024-01-08.log](https://github.com/tiddly-gittly/TidGi-Desktop/files/13859042/TidGi-2024-01-08.log)

这是清空之后，打开应用，填上账号。然后关闭应用，再打开应用，在wiki里选择同步wiki，然后发现是用test账号同步。生成的一个log文件。

**Comment by dongrentianyu** [comment]
```
{"function":"Authentication.set","key":"github-email","level":"debug","message":"Setting auth","timestamp":"2024-01-08T10:49:51.671Z","value":"spe......"}
{"function":"setUserInfos","level":"debug","message":"Storing authInfos","timestamp":"2024-01-08T10:49:51.671Z"}
{"function":"setUserInfos","level":"debug","message":"Storing authInfos","timestamp":"2024-01-08T10:50:06.514Z"}
```

其中能看到账号没有保存下来。这里我填的是英文账号，spectre-submarine@qq.com，但只保存了前面几个字母。

**Comment by linonetwo** [comment]
试试 https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.9.0-prerelease4 ，如果不行我也加了一些log

**Comment by dongrentianyu** [comment]
> 试试 https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.9.0-prerelease4 ，如果不行我也加了一些log

github email能正常保存了。不过账号要和github desktop里的保持一致。比如我在github desktop里设置的是纯数字的那个账号，那么在太记这边也要设置成纯数字的账号。

另一个是太微官方文档，估计要换一个源。https://tw-cn-doc.cpolar.top 停留在5.3.0，后面就没更新了。一直保持更新的是https://bramchen.github.io/tw5-docs/zh-Hans/ ，在其他源里打开的链接也是404

另一个提议是在自动提交里，Description可以增加成当地时间（在分或者在秒这个程度），这样看提交时也有个参考。虽然git可能包含这些，但要去查看git提交时间还是有点麻烦。好吧，主要是懒，不想写命令查看。

**Comment by linonetwo** [comment]
账号应该不用一致吧，会有啥问题吗？

反正没啥bug的话，我就发布正式版了

官方文档那个是因为是用html导入太记的，没有可以自动更新的nodejs版，得手动更新，就懒得更新了

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/1f7bcf0f-76eb-4cf7-815c-59c23685f23a)

是跟这里的账号保持一致。我这里填的是数字版的，太记那边就也要填数字版的。应该是没啥bug了。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/55f92072-c963-4cdb-973a-6bc08f608198)

就是这两个css文件不知道啥作用，也不知道为啥会加进来。一般要放在插件里更新的吧。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/109711900/f8729c10-3aa7-4de2-8e7a-eca502c0df46)

新建本地的话，没啥大问题。要说问题的话，可能就是侧边栏要调整一下，减少一些按钮之类的。以及那个文件目录要在插件里删除。因为依赖的那个Locator插件已经删除了。

**Comment by linonetwo** [comment]
![图片](https://github.com/tiddly-gittly/TidGi-Desktop/assets/3746270/316366c1-65e0-42d7-a6ac-9d70ab0ee11d)
文件目录看来没问题

**Comment by linonetwo** [comment]
账号那个啥意思，只有那个能保存下来？但是我试了随便填都能保存的

**Comment by dongrentianyu** [comment]
> 账号那个啥意思，只有那个能保存下来？但是我试了随便填都能保存的

能保存账号，但是如果用github同步的话，就要修改成跟github desktop一致的。这样太记才能正常在github desktop同步。

如果我在github destop那边写的是数字账号，而在太记这边写的是英文账号，两者就冲突了，就会使用test账号同步。

以上是针对全局账号设定来说的。

如果是特定仓库设置的特定账号，可以在github desktop仓库里和太记工作区配置里分别设置，两者保持一致就可以了。

抱歉，没说清楚。总之这个bug应该是修复了。
