### ISSUE TITLE
bug: 子工作区立即同步云端没有用

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TidGi-Desktop#502]
### Steps to Reproduce 复现方式

右键立即同步云端。但是主工作区可以同步子工作区

**Comment by dongrentianyu** [comment]
子wiki插件是删除了吗？怎么在cpl里没有找到，还是这个功能删除了？我记得以前是默认wiki就会装上这个插件的。

**Comment by linonetwo** [comment]
这个功能不需要插件，集成到太记里面了，不过还有bug

**Comment by dongrentianyu** [comment]
好，那就先不介绍了。等后续功能完善了，再介绍。
