### ISSUE TITLE
bug: 更新0.9版本之后打不开tidgi

### ISSUE THREAD

**Issue by king0billy** [tiddly-gittly/TidGi-Desktop#507]
### Environment 环境信息

win11
in Australia

### Description 描述

0.81release6更新0.9版本之后打不开tidgi，卸载删除注册表or安装msi版本也不行

### Steps to Reproduce 复现方式

安装0.81release6，运行0.81release6，下载0.9更新程序，然后安装完之后什么反应都没有也打不开

**Comment by king0billy** [comment]
重新安装0.8.1release6仍能正常运行。以管理员模式运行0.9.0也没反应。

Windows 11, version 22H2

**Comment by king0billy** [comment]
卸载0.81pre6再装0.9pre4可以正常打开，之后再装0.9就可以正常了

**Comment by king0billy** [comment]
```
Unhandled Promise Rejection
Error: ERR_ABORTED (-3) loading 'tidgi://lle9kwDF11yLsuahCmBcg#:'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:82635)
    at WebContents.navigationListener (node:electron/js2c/browser_init:2:82946)
    at WebContents.emit (node:events:529:35)
```

**Comment by linonetwo** [comment]
这是 log 里的报错吗？

**Comment by linonetwo** [comment]
之前 @dongrentianyu 好像遇到过

**Comment by dongrentianyu** [comment]
如果无法打开太记。可能是因为settings.json文件被清空了。

你可以在下面文件夹路径找到`C:\Users\你的用户名\AppData\Roaming\TidGi\settings\settings.json`，这个json文件。然后打开在里面写上`{}`，用记事本和vscode都可以，并保持一下。再重新打开太记。

打开太记后新建wiki或者导入原本的wiki。然后这个settings文件就会填充了。

多试几次。重点是保证这个setting文件夹里要有内容，有对花括号。我后面从0.9pre4升级到0.9正式版本时，也打不开。一看发现这个json文件又清空了。我就再填入`{}`，试了两次后就打开了。再导入原本的wiki。就能正常使用了。

**Comment by linonetwo** [comment]
这的确是个问题，之后得检查一下这个文件是不是为空了

**Comment by king0billy** [comment]
> 这的确是个问题，之后得检查一下这个文件是不是为空了
用CPL安装你的preview-glass报错：
preview-glass: Glassify Modification to the tobibeer/preview plugin, add inverse links, and make it auto-close
$:/plugins/linonetwo/preview-glass
0.6.0
此插件已经安装版本 0.5.7
出错: [404] Cannot find plugin $:/plugins/ooktech/dynamic-tables

**Comment by linonetwo** [comment]
preview-glass 好像有问题，我很久没用它了，不要在这里反馈，去 CPL 上链接里的这个插件的仓库反馈

**Comment by linonetwo** [comment]
我升级 0.9.1 的时候，我的配置也被删光了，手动修复 json 之后，一个个把 wiki 加回来……感觉得想办法备份一下这个配置文件吧
