### ISSUE TITLE
feature: 能直接在太记里缩放wiki吗？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#510]
### Description 描述

像在浏览器里使用那样缩放整个wiki。因为有的时候想要截图，不能缩放的话，感觉要截两张图片。而要在浏览器打开，又感觉麻烦，需要开启http和凭证。开了之后还要关掉。所以还是想直接在太记内部实现缩放功能。

**Comment by linonetwo** [comment]
<img width="315" alt="截屏2024-01-17 13 03 04" src="https://github.com/tiddly-gittly/TidGi-Desktop/assets/3746270/c095e4f1-9519-4974-b4c8-8e6da65d5692">

直接用浏览器缩放的快捷键应该就可以吧，虽然这个没法缩放图片，但是页面整体会缩放

**Comment by dongrentianyu** [comment]
没注意到。那这个也行，虽然不是直接用鼠标滚轮放大缩小的，但用起来也没问题。

**Comment by linonetwo** [comment]
还有截图不是有截图插件吗

**Comment by dongrentianyu** [comment]
截图插件的话，是直接截图整个条目，有时候不需要那么多。用截图插件之后还需要再处理一下。现在是用shareX软件来截图，效果还可以。截图之后还能直接进一步加工处理。

**Comment by dongrentianyu** [comment]
截图主要是为了新写的文档。

https://dongrentianyu.github.io/a-tiddlywiki-odyssey/

目前太记章节基本上写完了。你可以看看有没有什么要补充的，或者有没有写错的。后面章节争取过年前写完。

**Comment by oeyoews** [comment]
tiddliwiki作为标题不建议小写，应该这样 TiddlyWiki

**Comment by oeyoews** [comment]
中文文档的话，建议直接用太微代替

**Comment by dongrentianyu** [comment]
了解了。标题会用TiddlyWiki，正文的话，写作的时候，tiddlywiki和太微会混着用。我也不知道为啥潜意识里，会混在一起。

**Comment by linonetwo** [comment]
太记最近应该还会更新，所以就不用写具体版本号了。移动端也还没正式发布，也还会改，所以也不用写了。移动端主要是还不能直接创建wiki，得做到这一点了才能正式上架。

Github Desktop 可以展示一下清空 Changes，还有回滚 History ，这两个是用它的主要理由了。

发布可以贴一个 https://tidgi.fun/#:%E5%A4%AA%E8%AE%B0%E5%8A%9F%E8%83%BD%E6%89%8B%E5%86%8C%2F%E9%80%9A%E8%BF%87%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F%E5%BC%80%E8%AE%BE%E5%8D%9A%E5%AE%A2 的链接

**Comment by dongrentianyu** [comment]
好。我修改下。

我觉得太记可以自带一个转移wiki的功能。因为挪动工作区实际上就是把文件夹放到另一个文件夹里去，再导入到太记中。

网址穿透的那个，我补上链接吧。

github desktop的功能，嗯，应该写篇文章介绍下。
