### ISSUE TITLE
bug: [img[file:../image/xx.png]]引起五彩进度条一直加载，相对路径引用外部图片无法显示

### ISSUE THREAD

**Issue by king0billy** [tiddly-gittly/TidGi-Desktop#513]
### Environment 环境信息

win11 tidgi最新版本0.91

### Description 描述

五彩进度条一直在加载，右键无反应，长时间之后会黑屏
![2024-01-20_12-13-22_10-00_2520_1680_4105903_1](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52921954/e85cc232-adb4-4bdc-9a78-60d599ac392b)

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52921954/0a1aa3cc-402c-473b-80b7-d6e32a1b1a4b)

### Steps to Reproduce 复现方式

打开多几条tiddle, 重启后复现

**Comment by king0billy** [comment]
复现：打开如下tiddle出现问题
```
[img[封面按钮在右下角image.png]]
封面按钮在右下角

[img[file:../image/封面按钮在右下角image.png]]

[img[../image/封面按钮在右下角image.png]]

[ext[img|../image/封面按钮在右下角image.png]]

[[test img|../image/封面按钮在右下角image.png]]

<<image-basic img:"../image/封面按钮在右下角image.png" width:"90%" align:"center" caption:"" tooltip:"" alt:"">>

[img [https://images.rasalhague.net/hexxen/karte_markovia.jpg]]
```

**Comment by linonetwo** [comment]
是不是打开了所见即所得编辑器，所见即所得目前不支持有图片的条目。

可以用 vscode 打开这个条目在硬盘上的 tid 文件，然后删掉它的 sysiwyg 字段即可修复

**Comment by linonetwo** [comment]
还有 image-basic 是哪个插件提供的？

**Comment by king0billy** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52921954/0a0e4b44-abf8-4fde-bd93-e4c6c26b6782)


> 复现：打开如下tiddle出现问题
> 
> ```
> [img[封面按钮在右下角image.png]]
> 封面按钮在右下角
> 
> [img[file:../image/封面按钮在右下角image.png]]
> 
> [img[../image/封面按钮在右下角image.png]]
> 
> [ext[img|../image/封面按钮在右下角image.png]]
> 
> [[test img|../image/封面按钮在右下角image.png]]
> 
> <<image-basic img:"../image/封面按钮在右下角image.png" width:"90%" align:"center" caption:"" tooltip:"" alt:"">>
> 
> [img [https://images.rasalhague.net/hexxen/karte_markovia.jpg]]
> ```
1. slate write插件我早就已经禁用了，很多bug，包括但不限于导出所有html发红。
2. 这段代码的显示效果如图，很奇怪。 我也搞成功在wiki文件夹以外显示文件。
3. 两个已下架？的插件sp_spotlight或者oeyoews_tiddlywiki-fancybox-ui提供，我没搞懂。

**Comment by king0billy** [comment]
> 还有 image-basic 是哪个插件提供的？

就是这段代码引起五彩进度条加载。我暂时找不到来源了，是在tw官方论坛里面搜图片加载相关时复制的。。另外您能告诉我为什么图片不能正常显示吗，现在我已删了这段代码

**Comment by linonetwo** [comment]
这个是文件引用功能的文档，你看看了解完还有没有问题 https://tidgi.fun/#%E5%A4%AA%E8%AE%B0%E5%8A%9F%E8%83%BD%E6%89%8B%E5%86%8C%2F%E5%BC%95%E7%94%A8%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6

**Comment by king0billy** [comment]
相对路径不能访问wiki文件夹之外的图片啊? 
可是相对路径确实能打开wiki文件夹之外的链接
```
如 [ext[😲file: Supermemo | file:../html/index.htm]]  
index.htm 在C:\Users\22427\OneDrive\Documents\TiddlyWiki\html
wiki文件夹路径 C:\Users\22427\OneDrive\Documents\TiddlyWiki\HydroWood
```

**Comment by linonetwo** [comment]
你的是Windows吧，哪来的 /Users

还有你得把 file:// 打全了，看你都漏了

**Comment by king0billy** [comment]
> [ext[外部文件|C:/Users/22427/OneDrive/Documents/TiddlyWiki/image/test.png]]

[ext[外部文件|C:/Users/22427/OneDrive/Documents/TiddlyWiki/image/test.png]] 这个不用file://也行。

但是该用什么语法引用wiki文件夹之外的图片，并且能在tid文件里预览呢

**Comment by linonetwo** [comment]
用 img 而不是 ext 吧

**Comment by linonetwo** [comment]
[img[file://C:/Users/22427/OneDrive/Documents/TiddlyWiki/image/test.png]]  

这个呢

**Comment by king0billy** [comment]
> 件://C:/Users/22427/OneDrive/Documents/TiddlyWiki/image/test.png]]

没有任何效果，甚至连
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52921954/4240248b-0f1d-45b7-88f6-bcca7babfdef)
这个都不显示

**Comment by king0billy** [comment]
> [img[file://C:/Users/22427/OneDrive/Documents/TiddlyWiki/image/test.png]][img[文件://C:/Users/22427/OneDrive/Documents/TiddlyWiki/image/test.png]]
> 
> 这个呢

这是个bug，希望您能重视！

**Comment by linonetwo** [comment]
提供一个Github上的复现仓库吧，不然我这边没发现问题

**Comment by king0billy** [comment]
相关 https://github.com/tiddly-gittly/TidGi-Desktop/issues/562#issue-2316949036
