### ISSUE TITLE
bug: termux上使用最新太记npm包无法执行保存功能，之前的0.8.1pre6 可以

### ISSUE THREAD

**Issue by king0billy** [tiddly-gittly/TidGi-Desktop#514]
### Environment 环境信息

termux 0.118.0
kiwi browser or edge 最新版

### Description 描述

在android termux上使用最新nodejs版太记npm包无法执行保存功能，之前的0.8.1pre6 可以
**怀疑是destory-method版本的问题 报错和tiddlyweb相关**

### Steps to Reproduce 复现方式

用syncthing同步wiki文件夹到手机，[按照xp提供的nodejs流程安装](https://keatonlao.github.io/tiddlywiki-xp/#Serving%20TW5%20from%20Android)（已用npm额外装了@tidgi/tiddlywiki）并运行

### Additional Context 额外上下文

![IMG_20240123_233500](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52921954/cad3f43c-1790-42d8-b053-da7ea472f8d9)

![IMG_20240123_233511](https://github.com/tiddly-gittly/TidGi-Desktop/assets/52921954/9a537ccc-ca06-4624-bda7-8319783a1494)

**Comment by linonetwo** [comment]
直接用官方 tiddlywiki 包即可，我发的那个是预发布版的，可能不大稳定吧。

还有注意看一下文件夹里 linonetwo 开头的插件，有没有把 tidgi SyncAdaptor 之类的东西同步过去了，可能会导致 tiddlyweb SyncAdaptor 工作不正常

**Comment by linonetwo** [comment]
可以参考  https://wiki.onetwo.ren/%E5%9C%A8%E6%89%8B%E6%9C%BA%E4%B8%8A%E8%BF%90%E8%A1%8C%E5%A4%AA%E5%BE%AEnodejs%E5%8D%9A%E5%AE%A2 ，这个和太记应该没有关系
