### ISSUE TITLE
bug: 始终全屏

### ISSUE THREAD

**Issue by wsqstar** [tiddly-gittly/TidGi-Desktop#519]
### Environment 环境信息

TidGi (win32)
Version v0.9.1

Electron Version: 28.1.0
Node Version: 18.18.2
Chromium Version: 120.0.6099.109

### Description 描述

始终全屏
没有菜单栏
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/24500520/de8ae332-5b98-4901-9d3d-4c3c2c2235ae)

### Steps to Reproduce 复现方式

不知道。可能和上一个bug相关。

**Comment by wsqstar** [comment]
证实是太记小窗口 但是没有任何提示是在小窗口（笑死

**Comment by linonetwo** [comment]
f11
