### ISSUE TITLE
bug: TAGI 乱码

### ISSUE THREAD

**Issue by wsqstar** [tiddly-gittly/TidGi-Desktop#520]
### Description 描述

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/24500520/4095f1b3-2251-48fd-a9f9-e6203aaac201)

### Steps to Reproduce 复现方式

按照教程 https://tidgi.fun/AI 就会出现这样的情况

**Comment by linonetwo** [comment]
等接入中文模型就好了 https://github.com/tiddly-gittly/TidGi-Desktop/issues/465#issuecomment-1911740516

**Comment by linonetwo** [comment]
最新预发布版可以用中文模型了，有空我在官网更新用法
