### ISSUE TITLE
bug: 自动添加[ext 前缀

### ISSUE THREAD

**Issue by wsqstar** [tiddly-gittly/TidGi-Desktop#522]
### Environment 环境信息

TidGi (win32)
Version v0.9.1

Electron Version: 28.1.0
Node Version: 18.18.2
Chromium Version: 120.0.6099.109

### Description 描述

index 自动添加[[ext 前缀
比如[ceshi|github.com]] 在保存后会自动变为[[ext[ceshi|github.com]]
- 观察到[ext[是拓展语法 但是本身并没有安装任何插件。 在保存后即出现此状况。

### Steps to Reproduce 复现方式

保存之后即出现此状况

**Comment by linonetwo** [comment]
是所见即所得的功能 https://github.com/tiddly-gittly/slate-write ，这是正常的，因为外链就是推荐加 ext，不用担心。
