### ISSUE TITLE
feature: 本地同步

### ISSUE THREAD

**Issue by luyuduan** [tiddly-gittly/TidGi-Desktop#523]
### Description 描述

体验了这个项目的软件，希望有以下功能
以下是我笔记的一部分：

-   平时手机看视频，浏览文章，希望稍后在电脑上看，就暂时记录在`微信 - 文件传输助手`。但是

    -   ！偶尔会遗漏同步
    -   ！本质还是聊天记录，能同步增加，不能同步删除

    试过微力同步、SyncTrayzor等同步软件，小书匠、思源笔记等支持局域网同步的笔记软件。但是

    -   本质还是对[.md]文件操作，不能按条删除，编辑增删麻烦

-   所以需求如下：

    -   满足TODO形式
        -   支持按条记录，按条删除。就像微信对话框那样
        -   支持链接跳转，支持各种形式的记录
        -   支持修改每条里的内容。[可选]
    -   局域网同步
        -   不需要注册登录，就可以局域网同步。就像微力同步、SyncTrayzor那样
        -   增删改可以同步，没必要实时同步，但是有关联设备上线，保存时自动同步。就像微力同步、SyncTrayzor那样
        
[这个项目](https://github.com/yunusemrealpak/flutter_todo_with_sync_backup)有点相关，但是没有安装包

或者有没有已有的轮子推荐

**Comment by luyuduan** [comment]
目前滴答清单是最接近完美的，但是必须登录，不够隐私

**Comment by linonetwo** [comment]
可以直接把网页分享给 https://github.com/tiddly-gittly/TidGi-Mobile ，会形成一个条目。之后在电脑上查看最近的条目即可。

用 https://github.com/tiddly-gittly/tw-mobile-sync CPL 上的这个插件可以局域网同步。不过太记移动端最近还经常改动，更新版本前记得提前备份到电脑端，然后再更新，因为更新后之前的知识库可能会打不开（但电脑端永远是稳的）

**Comment by luyuduan** [comment]
尝试了半个小时，不会安装插件，教程看不懂，很多链接打不开，比如这个[CPL](https://tw-cpl.netlify.app/#linonetwo%2Ftw-mobile-sync:linonetwo%2Ftw-mobile-sync%20Welcome%20Index)或者卡顿，有点生气自己浪费时间，看/学习这些晦涩难懂的教程。可能目标人群不适合

一点建议
1. 教程过多且复杂繁琐
 - 优点：用户粘性强，学会了适应了，就不易割舍
 - 缺点：门槛高，不容易学会
 - Notion、Obsidian 我没学会，甚至不敢接触，感觉就像是PS、AutoCAD之类的专业软件，没有背景难以入门
 - 最好的教程是方便的，符合直觉的。就像插件安装，直接给出安装入口，搜索安装，两步搞定，就像vscode那样。不好的呢，在各种链接间跳转、学习，看图比较，就像

2. 设计复杂，细节过多
 - 可以对比下Typero和小书匠的设计，有时候功能很多但是急于展示可能适得其反，可能开发者觉得功能这么丰富，稍微展示一些。但是对于用户来说，一上来就给出各种概念容易失去耐心。最好是需要时再去搜索功能。当然需求也可以由开发者创造
- 对于笔记类，我一般是先使用一款软件的通用部分，而不想一上来就去学习一款软件的独特点。有些软件没有提示，有些软件更新时给出更新特性，有些软件会有每日小提示，有些软件会处处展示新概念新特性，给出各种教程。
- 小书匠的花活很多，设计也很新奇，但是不厌其烦的展示就，，，，就像一些超市的销售人员，你看着这个，再看看这个，还有这个。开发者的心态可以理解，我有这些好功能，你来试一试，不会用？这里还有教程，跳过去看看？又回到了建议1。
- 可能是开发比较悠久，温知笔记没有这个问题，可以参考
- 比如下图中你看到的是什么？初看似乎是一款前端设计软件
  ![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/37297576/1c40e46a-972d-4964-bbbc-6ceacd3490d7)


![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/37297576/7e75b9d7-dd84-4f33-929d-4aeeeac92633)
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/37297576/d41682f3-7f27-4b8b-af79-e4f74b1d2fbb)
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/37297576/3ee7a0d9-22e3-4786-a7cd-9053a27fe770)

~~最后给一句可能引起开源开发人生气的一句气话：啥也不是，太麻烦了，不用了~~

**Comment by linonetwo** [comment]
有建议可以去论坛发帖，这里关掉的issue就不再关注了。

**Comment by luyuduan** [comment]
定位和我的需求可能不太合适，我再看看别的
