### ISSUE TITLE
bug: 升级了版本后无法打开原有的Wiki了

### ISSUE THREAD

**Issue by jinhy1125** [tiddly-gittly/TidGi-Desktop#528]
### Environment 环境信息

TidGi (win32)
Version v0.9.3

Electron Version: 28.1.0
Node Version: 18.18.2
Chromium Version: 120.0.6099.109

### Description 描述

之前的版本遇到了如果连不上 github 就会闪退，然后无法重新打开的问题，就升级了最新的版本。
但是重新手动加载了 wiki 目录后无法正常显示了。页面一直是空白内容。
F12 控制台有报错。

![Snipaste_2024-02-20_10-49-41](https://github.com/tiddly-gittly/TidGi-Desktop/assets/11604546/3882848d-ad0f-411b-9f56-a3088481e640)

### Steps to Reproduce 复现方式

1. 老版本升级（老版本忘记是啥了）
2. 加载原有目录
3. 加载空白报错

**Comment by linonetwo** [comment]
那个报错是因为wiki没加载成功，不是原因。

最新版我这都没问题，你看是不是文件夹选错了，需要选择包含了 tiddlers/ 文件夹的那个文件夹

**Comment by linonetwo** [comment]
设置里有开发者工具，看看log里有什么错

**Comment by jinhy1125** [comment]
刚重新打开 app，截图的 error 日志

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/11604546/24998500-edd6-470b-bc81-3693293e69cf)

**Comment by linonetwo** [comment]
log 文件夹旁边有 setting 文件夹，也可以把里面的 setting json 删了试试

**Comment by jinhy1125** [comment]
删除了 setting 中的所有 json，移除了工作区（没删除目录），重新添加后还是这样。

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/11604546/91769548-d229-4463-a003-afc58cb2d96a)

最新的 log 截图：

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/11604546/b668f5a7-0ded-484b-9465-d2e5729233d6)

**Comment by linonetwo** [comment]
也有 wiki 的 log，看看 wiki 是否成功启动了。这可能是某个插件在新版上不能运行了，比较你新建wiki还是能用的吧

**Comment by linonetwo** [comment]
再点击一下左边工作区图标试试

**Comment by jinhy1125** [comment]
是的，新建wiki还是没问题的，点击左边工作区图标还是没反应。

清了所有log，然后点了下那个wiki的重启服务。日志如下：

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/11604546/f4f08e08-a8ad-47eb-8348-91d9000e90cf)

**Comment by linonetwo** [comment]
不是这个log，是类似这种 wiki 结尾的log，会说是哪个插件报错了之类的

<img width="1076" alt="截屏2024-02-23 12 18 06" src="https://github.com/tiddly-gittly/TidGi-Desktop/assets/3746270/d2cdef4d-f1ec-4542-8155-e4865543fe5a">

如果是启动了，你急着用的话，可以在工作区设置里最底下，服务器设置里开启httpapi，重启后工作区设置里会显示网页，就可以在浏览器打开了。

如果你这个知识库是公开的，给个 Github 地址我可以帮你看看。

**Comment by dongrentianyu** [comment]
我升级版本后，能正常重新导入原有wiki。

你之前的wiki是用太记新建的吗？还是通过html转换后导入进去的？

**Comment by heavenkiller2018** [comment]
I have the same problem, and all related logs are the following:

TidGi-2024-02-25.log

```ini
{"level":"info","message":"App booting","timestamp":"2024-02-24T23:02:26.121Z"}
{"level":"info","message":"Quitting dut to we only allow one instance to run.","timestamp":"2024-02-24T23:02:26.123Z"}
{"level":"info","message":"Checking Setting file format.","timestamp":"2024-02-24T23:02:26.147Z"}
{"level":"info","message":"Setting file format good.","timestamp":"2024-02-24T23:02:26.148Z"}
{"level":"info","message":"App booting","timestamp":"2024-02-24T23:02:26.287Z"}
{"LOCAL_GIT_DIRECTORY":"C:\\Users\\11507\\AppData\\Local\\tidgi\\app-0.9.3\\resources\\node_modules\\dugite\\git","function":"Git.initWorker","level":"debug","message":"initial gitWorker with  722.index.worker.js","timestamp":"2024-02-24T23:02:26.290Z"}
```



zJCcaFk7GEzSxg-HGPFkK-Computer-Science-2024-02-25.log

```ini
{"level":"info","message":"","resultType":"observable","timestamp":"2024-02-24T23:04:01.540Z","type":"running","uid":"19"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:01.541Z","type":"result","uid":"19"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:01.542Z","type":"result","uid":"19"}
{"level":"info","message":"","resultType":"observable","timestamp":"2024-02-24T23:04:01.542Z","type":"running","uid":"20"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:01.542Z","type":"result","uid":"20"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:04.316Z","type":"result","uid":"20"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:04.328Z","type":"result","uid":"20"}
{"function":"startNodeJSWiki","level":"info","message":"syncer-server-filesystem: Dispatching 'save' task: $:/StoryList\n","timestamp":"2024-02-24T23:04:04.328Z"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:04.330Z","type":"result","uid":"20"}
{"function":"startNodeJSWiki","level":"info","message":"Serving on http://0.0.0.0:5214\n","timestamp":"2024-02-24T23:04:04.331Z"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:04.331Z","type":"result","uid":"20"}
{"function":"startNodeJSWiki","level":"info","message":"(press ctrl-C to exit)\n","timestamp":"2024-02-24T23:04:04.331Z"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:04.331Z","type":"result","uid":"20"}
{"level":"info","message":"","resultType":"promise","timestamp":"2024-02-24T23:04:04.433Z","type":"running","uid":"21"}
{"level":"info","message":"","resultType":"promise","timestamp":"2024-02-24T23:04:04.436Z","type":"running","uid":"22"}
{"complete":"true","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:05.159Z","type":"result","uid":"22"}
{"level":"info","message":"","resultType":"promise","timestamp":"2024-02-24T23:04:05.288Z","type":"running","uid":"23"}
{"complete":"true","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:05.897Z","type":"result","uid":"23"}
{"complete":"undefined","level":"info","message":"","payload":"[object Object]","timestamp":"2024-02-24T23:04:06.003Z","type":"result","uid":"20"}
{"function":"startNodeJSWiki","level":"info","message":"syncer-server-filesystem: Dispatching 'save' task: $:/config/Server/AllowAllExternalFilters\n","timestamp":"2024-02-24T23:04:06.003Z"}
{"complete":"true","level":"info","message":"","payload":"undefined","timestamp":"2024-02-24T23:04:06.003Z","type":"result","uid":"21"}

```

**Comment by jinhy1125** [comment]
> 我升级版本后，能正常重新导入原有wiki。
> 
> 你之前的wiki是用太记新建的吗？还是通过html转换后导入进去的？

啊对 我之前是导入的，先写了，后面发现了太记

**Comment by linonetwo** [comment]
我试试导入的有没有问题。不过看 @heavenkiller2018 的 log ， wiki 已经成功启动了，可以通过 http 访问网页版 localhost:5214

有可能是左边工作区切换的bug，导致没显示出来

**Comment by heavenkiller2018** [comment]
where is "服务器设置里开启httpapi"?  I can't find it in current version! 

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45555611/1ffac092-5a7e-42f7-96e8-b05a197a3303)

**Comment by heavenkiller2018** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45555611/f8f9cc52-847c-415e-8185-3bda776eb148)


![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45555611/c5041e07-85ef-45c1-a6e1-8c76f3f78b29)


workspace "wiki" (a demo) is normal, but my working workspace "Computer Science" is pending.

**Comment by linonetwo** [comment]
@heavenkiller2018 rigit click workspace icon - workspace setting, and it is on the bottom, server settings, expand it, there is HTTP API setting.

I don't know what happened, because it works fine on my wiki.

**Comment by heavenkiller2018** [comment]
![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45555611/17612b25-2dcf-487e-8943-95bfde0f07fb)

“HTTP API setting” is found at rigit click workspace icon => Current Workspace => Config Workspace



![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45555611/fffb9696-5066-4046-a41d-465f5a3f9d40)

But even using a browser, it still won't open.

I feel like it's probably an issue with the plugin. But why aren't the plugin errors recorded in the log? Each version upgrade seems to cause some plugin compatibility issues, leading to a poorer user experience. I hope this issue can be optimized.

**Comment by linonetwo** [comment]
I can't fix this, because nobody provide a repo.

**Comment by linonetwo** [comment]
@jinhy1125 复现仓库有了吗

**Comment by jinhy1125** [comment]
> @jinhy1125 复现仓库有了吗

目前在搞一些严肃项目，得等等有时间搞一下😂

**Comment by linonetwo** [comment]
Seems I have fixed this somehow?
