### ISSUE TITLE
bug: 插件没有加载

### ISSUE THREAD

**Issue by sisyphus1212** [tiddly-gittly/TidGi-Desktop#543]
### Environment 环境信息

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45515761/0d766e26-5df5-48f7-b2f6-6f1acbf2b007)

### Description 描述

bug: 插件没有加载

### Steps to Reproduce 复现方式

bug: 插件没有加载

### Additional Context 额外上下文

bug: 插件没有加载

**Comment by linonetwo** [comment]
https://talk.tiddlywiki.org/t/what-happened-with-tw-cpl-repo/9454

https://tw-cn.netlify.app/#%2524%253A%252Fplugins%252FGk0Wk%252FCPL-Repo

**Comment by sisyphus1212** [comment]
这个插件源咋用？

**Comment by sisyphus1212** [comment]
大佬出一期插件源使用的教程吧，这个插件配置着实难搞

**Comment by linonetwo** [comment]
可以看B站最新一期视频，里面有提到 https://www.bilibili.com/video/BV1MD421578F/?spm_id_from=333.999.0.0
