### ISSUE TITLE
bug: github 同步好像不生效呀

### ISSUE THREAD

**Issue by sisyphus1212** [tiddly-gittly/TidGi-Desktop#544]
### Environment 环境信息

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45515761/1048bbcd-5022-49e0-bd11-cb99b368b8bf)

### Description 描述

编辑卡片后，右键没看到同步到远端的选项

### Steps to Reproduce 复现方式

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45515761/51f99560-f29e-437b-a5b5-1478eccd25a0)
这个选项一直不生效

**Comment by linonetwo** [comment]
工作区设置里，有改为远程同步工作区，你可能没开

**Comment by linonetwo** [comment]
怎么只提问题却不回复？关了
