### ISSUE TITLE
bug: 中文插件源不生效

### ISSUE THREAD

**Issue by sisyphus1212** [tiddly-gittly/TidGi-Desktop#545]
### Environment 环境信息

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45515761/0b42a3f9-68fc-40e4-880f-cf1ef7768ba2)

### Description 描述

github 中文插件源无法使用

### Steps to Reproduce 复现方式

github 中文插件源无法使用

### Additional Context 额外上下文

github 中文插件源无法使用

**Comment by sisyphus1212** [comment]
无法加载

**Comment by linonetwo** [comment]
这个遗弃了，用cpl。
