### ISSUE TITLE
bug: 这个图标可以调小吗

### ISSUE THREAD

**Issue by sisyphus1212** [tiddly-gittly/TidGi-Desktop#546]
### Environment 环境信息

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45515761/95934adb-946c-485b-9435-de0712e12704)

### Description 描述

这个图标可以调小吗

### Steps to Reproduce 复现方式

这个图标可以调小吗

### Additional Context 额外上下文

这个图标可以调小吗

**Comment by linonetwo** [comment]
这种问题去论坛问吧
