### ISSUE TITLE
bug: 白板在全屏下无法退出

### ISSUE THREAD

**Issue by sisyphus1212** [tiddly-gittly/TidGi-Desktop#552]
### Environment 环境信息

![image](https://github.com/tiddly-gittly/TidGi-Desktop/assets/45515761/6e368284-5285-4eb9-a65d-f974ed77b253)

### Steps to Reproduce 复现方式

进如全屏模式后无法退出

**Comment by linonetwo** [comment]
这种问题论坛或Q群问，不许开issue

**Comment by sisyphus1212** [comment]
> 这种问题论坛或Q群问，不许开issue

要不直接在这里开个主题用于讨论，不然感觉信息很分散，还要注册啥的，感觉好麻烦
