### ISSUE TITLE
feature:  能否提供 "URL" 内容类型的文档

### ISSUE THREAD

**Issue by LeXwDeX** [tiddly-gittly/TidGi-Desktop#554]
因为知识图谱中会想管理到URL这种资源。
个人认为这种资源比较独特，它既可以作为收藏夹使用也可以作为知识图谱的一个部分。

---

或者说是我还未发现其实有平替的方案吗。

**Comment by linonetwo** [comment]
和太记无关，去论坛问吧，我知道但我不在这里回答
