### ISSUE TITLE
配置LLaMA后不能提问

### ISSUE THREAD

**Issue by yankaifyyy** [tiddly-gittly/TidGi-Desktop#555]
### Environment 环境信息

Win11
TidGi
Llama3-8B-Chinese-Chat-q8
chinese-llama-2-13B.Q8_0

### Description 描述

尝试使用LLaMA2和LLaMA3作后端，前段弹窗Rhe provided Jinja template failed that sanity test: Error: Some input messages are not present in the generated Jinja template output

### Steps to Reproduce 复现方式

将llama2或llama3软链接到制定目录下（Roaming目录），配置软件，  提问就包错

**Comment by linonetwo** [comment]
有用CPL更新插件到最新版吗

**Comment by linonetwo** [comment]
这个功能新版要去掉了，因为又慢又笨，还不如用在线的 API。
