### ISSUE TITLE
bug: react条目会导致wiki启动报错

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TidGi-Desktop#583]
### Environment 环境信息

[TidGi-2024-09-08.log](https://github.com/user-attachments/files/16921940/TidGi-2024-09-08.log)

Version v0.10.3

Electron Version: 31.1.0
Node Version: 20.14.0
Chromium Version: 126.0.6478.114

### Description 描述

不清楚啥bug

Unhandled Promise Rejection
Error: [1;31mError executing boot module react-dom: Error: Cannot find module 'react'
Require stack:
- C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js
- C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/app.asar.unpacked/.webpack/main/543.index.worker.js
Error: Cannot find module 'react'
Require stack:
- C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js
- C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/app.asar.unpacked/.webpack/main/543.index.worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at Function.c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at a (C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/app.asar.unpacked/.webpack/main/543.index.worker.js:2:445925)
    at Object.$tw.modules.execute (C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:919:11)
    at require (C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:878:24)
    at react-dom:1:129592
    at react-dom:1:129713
    at react-dom:2:4[0m
    at Object.next (C:/Users/34656/AppData/Local/tidgi/app-0.10.3/resources/app.asar/.webpack/main/index.js:2:2087687)

### Steps to Reproduce 复现方式

现在一启动打开这个wiki就会弹出报错。
![image](https://github.com/user-attachments/assets/905ac0e3-f903-4eae-9d02-5ba4321866a2)

**Comment by dongrentianyu** [comment]
![image](https://github.com/user-attachments/assets/48c9c2af-6296-4c1f-9c93-284b8c47985a)

好像跟这个隐藏菜单栏有关。

**Comment by dongrentianyu** [comment]
其他wiki都是正常打开使用的。

**Comment by dongrentianyu** [comment]
![image](https://github.com/user-attachments/assets/8a358491-84cb-49d2-ad8b-3055b77f695d)

终于正常打开了。

可能有以下几种原因。一个是图片空白导致加载不出来。因为我是把自己之前好多分散的wiki条目导出后导入进来。有些图片就导出不了，变成空白了。可能导致加载不出来。

另一个则可能是一些之前用过的宏，在现在新版本的tiddlywiki上，可能用不了。 

![image](https://github.com/user-attachments/assets/5db157a7-60c8-42c1-860c-289776a46b2c)
 
但还有一种可能是我导入了一个react的条目。我感觉这个原因跟报错的log最相近。 

![image](https://github.com/user-attachments/assets/e06dc14c-aba4-466f-bddf-e6f106236ac0)

**Comment by dongrentianyu** [comment]
![image](https://github.com/user-attachments/assets/044792f4-5a6e-410f-996f-029e8bf293ee)

破案了，就是react条目导致的。复现方式就是新建一个wiki，然后新建一个react条目。再重新启动就会弹出报错。

**Comment by linonetwo** [comment]
应该是 react 条目和 react 插件里的条目重名了，导致出错了。

**Comment by dongrentianyu** [comment]
以前写的时候没这个问题。就怕还有其他类似的词语。

**Comment by linonetwo** [comment]
各种插件用到的基础库估计都这样，mermaid 可能也是，这个没办法。只能说及时备份，出错了回滚。

**Comment by linonetwo** [comment]
一般这个问题也不会影响到中国人的条目
